# Proposición y su negación {#sec-proposicion}

La unión de dos o más palabras nos permite crear una oración o enunciado, como se muestra en el @exm-quimica.

::: {#exm-quimica}
*La química es la ciencia que estudia la materia ordinaria.*
:::

Cuando un enunciado puede ser verdadero (V) o falso (F), obtenemos una **proposición** (cf. *Introducción a la teoría de conjuntos*). Usando la lógica, podemos determinar si un enunciado es V o F. Ahora bien, si esto se dificulta, podemos convertir el enunciado en una pregunta, si esta puede responderse con un sí o con un no, entonces es una proposición. Convirtamos el @exm-quimica en una pregunta:

::: {#exm-quimica-pregunta}
## Pregunta de control
*¿La química es la ciencia que estudia la materia ordinaria?*
:::

Al observar el @exm-quimica-pregunta, identificamos que puede contestarse con un sí o con un no. Esto nos indica que el @exm-quimica es una proposición.

Hay enunciados que no son proposiciones, como se ve en el @exm-saludo, en el cual no podemos determinar si el enunciado es V o F, dado que se trata de una expresión de saludo.

::: {#exm-saludo}
## Expresión coloquial
*Hola, ¿cómo estás?*
:::

La proposición del @exm-quimica puede etiquetarse con una letra; en esta ocasión será la letra *P*. La proposición *P* puede tener su negación, como se observa en el @exm-quimica-negacion. La negación se representa con el signo $\neg$; por tanto, la negación de *P* queda como $\neg P$. $\neg P$ se lee como "no *P*" o "la negación de *P*" (cf. *Introducción a la teoría de conjuntos*).

::: {#exm-quimica-negacion}
## Negación lógica
*La química **no** es la ciencia que estudia la materia ordinaria.*
:::

Las proposiciones *P* y $\neg P$ pueden valorarse como V o F. Si *P* es V, entonces $\neg P$ es F; y si *P* es F, entonces $\neg P$ es V. Esto se puede representar con una **tabla de verdad** (cf. *Introducción a la teoría de conjuntos*), como se observa en la @tbl-verdad-negacion.

| $P$ | $\neg P$ |
| :---: | :---: |
| V | F |
| F | V |

: Tabla de verdad para las proposiciones $P$ y $\neg P$ {#tbl-verdad-negacion}