<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Capítulo 7 · Tabla periódica y propiedades periódicas – Nous</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../02_quimica/08-enlace-quimico-i-conceptos-fundamentales.html" rel="next">
<link href="../02_quimica/06-estructura-electronica-del-atomo.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-53aca5cea238aca1de29c5a91d105b8d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-title">Capítulo 7 · Tabla periódica y propiedades periódicas</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Nous</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nous</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Conjuntos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_conjuntos/00_proposicion_negacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Proposición y su negación</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Química</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/01-historia-de-la-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 1 · La química en la historia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/02-materia-y-medicion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 2 · La materia y su medición</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/03-atomos-moleculas-e-iones.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 3 · Átomos, moléculas e iones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/04-estequiometria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 4 · Estequiometría: moles, fórmulas y ecuaciones químicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/05-reacciones-en-disolucion-acuosa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 5 · Reacciones en disolución acuosa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/06-estructura-electronica-del-atomo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 6 · Estructura electrónica del átomo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/07-tabla-periodica-y-propiedades-periodicas.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Capítulo 7 · Tabla periódica y propiedades periódicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/08-enlace-quimico-i-conceptos-fundamentales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 8 · Enlace químico I: conceptos fundamentales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/09-enlace-quimico-ii-geometria-molecular-y-teorias-de-enlace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 9 · Enlace químico II: geometría molecular y teorías de enlace</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/10-gases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 10 · Gases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/11-termoquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 11 · Termoquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/12-liquidos-fuerzas-intermoleculares-y-solidos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 12 · Líquidos, fuerzas intermoleculares y sólidos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/13-disoluciones-y-propiedades-coligativas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 13 · Disoluciones y propiedades coligativas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/14-cinetica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 14 · Cinética química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/15-equilibrio-quimico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 15 · Equilibrio químico</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/16-acidos-y-bases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 16 · Ácidos y bases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/17-equilibrios-acido-base-y-solubilidad.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 17 · Equilibrios ácido-base y de solubilidad: aplicaciones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/18-termodinamica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 18 · Termodinámica química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/19-electroquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 19 · Electroquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/20-quimica-nuclear.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 20 · Química nuclear</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/21-quimica-de-los-no-metales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 21 · Química de los no metales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/22-quimica-de-los-metales-de-transicion-y-quimica-de-coordinacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 22 · Química de los metales de transición y química de coordinación</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Biología</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_biologia/01_base_fisica_herencia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">La base física de la herencia</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#la-ley-periódica-y-la-forma-de-la-tabla" id="toc-la-ley-periódica-y-la-forma-de-la-tabla" class="nav-link" data-scroll-target="#la-ley-periódica-y-la-forma-de-la-tabla">La ley periódica y la forma de la tabla</a></li>
  <li><a href="#carga-nuclear-efectiva" id="toc-carga-nuclear-efectiva" class="nav-link" data-scroll-target="#carga-nuclear-efectiva">Carga nuclear efectiva</a></li>
  <li><a href="#radios-atómicos-y-radios-iónicos" id="toc-radios-atómicos-y-radios-iónicos" class="nav-link" data-scroll-target="#radios-atómicos-y-radios-iónicos">Radios atómicos y radios iónicos</a></li>
  <li><a href="#energía-de-ionización" id="toc-energía-de-ionización" class="nav-link" data-scroll-target="#energía-de-ionización">Energía de ionización</a></li>
  <li><a href="#afinidad-electrónica" id="toc-afinidad-electrónica" class="nav-link" data-scroll-target="#afinidad-electrónica">Afinidad electrónica</a></li>
  <li><a href="#carácter-metálico-metales-no-metales-y-metaloides" id="toc-carácter-metálico-metales-no-metales-y-metaloides" class="nav-link" data-scroll-target="#carácter-metálico-metales-no-metales-y-metaloides">Carácter metálico: metales, no metales y metaloides</a></li>
  <li><a href="#tendencias-en-los-grupos-1a-y-2a" id="toc-tendencias-en-los-grupos-1a-y-2a" class="nav-link" data-scroll-target="#tendencias-en-los-grupos-1a-y-2a">Tendencias en los grupos 1A y 2A</a></li>
  <li><a href="#no-metales-seleccionados" id="toc-no-metales-seleccionados" class="nav-link" data-scroll-target="#no-metales-seleccionados">No metales seleccionados</a></li>
  <li><a href="#ejemplo-resuelto-el-bismuto-miembro-pesado-del-grupo-5a" id="toc-ejemplo-resuelto-el-bismuto-miembro-pesado-del-grupo-5a" class="nav-link" data-scroll-target="#ejemplo-resuelto-el-bismuto-miembro-pesado-del-grupo-5a">Ejemplo resuelto: el bismuto, miembro pesado del grupo 5A</a></li>
  <li><a href="#preguntas-y-ejercicios" id="toc-preguntas-y-ejercicios" class="nav-link" data-scroll-target="#preguntas-y-ejercicios">Preguntas y ejercicios</a></li>
  <li><a href="#solucionario" id="toc-solucionario" class="nav-link" data-scroll-target="#solucionario">Solucionario</a></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen">Resumen</a></li>
  <li><a href="#autoevaluación" id="toc-autoevaluación" class="nav-link" data-scroll-target="#autoevaluación">Autoevaluación</a></li>
  <li><a href="#enlace-al-próximo-capítulo" id="toc-enlace-al-próximo-capítulo" class="nav-link" data-scroll-target="#enlace-al-próximo-capítulo">Enlace al próximo capítulo</a></li>
  <li><a href="#glosario-acumulativo" id="toc-glosario-acumulativo" class="nav-link" data-scroll-target="#glosario-acumulativo">Glosario acumulativo</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-title">Capítulo 7 · Tabla periódica y propiedades periódicas</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>El capítulo anterior cerró con una promesa: las configuraciones electrónicas explican la forma de la tabla periódica, y la posición de cada elemento predice su comportamiento <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. Este capítulo cumple esa promesa mostrando primero cómo se construyen los periodos y los grupos, y recorriendo después las propiedades que convierten la tabla en un instrumento predictivo <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.1</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.2</a>)</span>.</p>
<p>La tabla no nació de un solo golpe: en 1817 Döbereiner agrupó elementos de propiedades semejantes en <strong>tríadas</strong> de tres, y en 1863 Newlands propuso la <strong>ley de las octavas</strong>, según la cual cada octavo elemento de la lista por peso atómico repetía el comportamiento químico <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. Ambos esfuerzos pasaron casi desapercibidos, y fue Mendeleev quien en 1869 dio con el ordenamiento que finalmente se impuso, la ley periódica que el capítulo 6 ya presentó <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>La aceptación de la tabla de Mendeleev se selló con las predicciones: el eka-aluminio, que resultó ser el galio, descubierto en 1875, y el eka-boro, que fue el escandio, de 1879, trajeron propiedades muy cercanas a las anunciadas <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>)</span>. Conviene, sin embargo, registrar la discrepancia de énfasis de las fuentes: mientras <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.1</a>)</span> subraya la simultaneidad de los esquemas de Mendeleev y Meyer, <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span> distingue el sistema de diecisiete columnas de 1869 del de ocho columnas de 1871, y ambas lecturas conviven sin contradecirse <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.1</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
</section>
<section id="la-ley-periódica-y-la-forma-de-la-tabla" class="level2">
<h2 class="anchored" data-anchor-id="la-ley-periódica-y-la-forma-de-la-tabla">La ley periódica y la forma de la tabla</h2>
<p>El sistema de 1869 de Mendeleev ordenaba los elementos conocidos en una tabla de diecisiete columnas, semejante a la moderna pero sin gases nobles, y la revisión de 1871 movió diecisiete elementos a posiciones que corregían sus pesos atómicos aceptados, al descubrirse pequeñas y grandes equivocaciones en las masas medidas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>En el mismo año 1871, Mendeleev y, de forma independiente, Meyer propusieron la tabla de ocho columnas, obtenida al partir cada periodo largo en dos series de siete elementos y un grupo central <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. Esa estructura de ocho columnas, con las letras a y b añadidas a los números romanos, sobrevive en la notación actual <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>Mendeleev reservó casillas vacías para elementos aún no descubiertos y nombró seis con el prefijo sánscrito eka, “uno”: eka-boro, eka-aluminio, eka-silicio, eka-manganeso, dvi-manganeso y eka-teluro <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. Los tres primeros corresponden al escandio, al galio y al germanio, descubiertos poco después por otros químicos con las propiedades anunciadas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. Los tres últimos, tecnecio, renio y polonio, se obtuvieron o fabricaron en el siglo veinte y también respondieron a las predicciones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>La ley periódica cobró además un uso espectroscópico: Bohr señaló que el elemento de número atómico 72 debía parecerse al circonio, y Hevesy y Coster, siguiendo esa observación, examinaron minerales de circonio y aislaron en ellos el elemento desconocido, el hafnio, en 1923 <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. La tabla dejó de clasificar lo conocido y pasó a anticipar lo que faltaba por descubrir <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>El grupo cero se incorporó después de los demás porque sus habitantes no reaccionaban con nada: Rayleigh y Ramsay aislaron en 1894 y los años siguientes el helio, el neón, el argón, el criptón y el xenón, y hubo que fundar para ellos una columna nueva <span class="citation" data-cites="pauling1988 brock2015">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>; <a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>)</span>. La inercia de esos gases se explicó más tarde con la configuración: sus subcapas s y p estaban completamente llenas, y ese arreglo, que anticipa la regla del octeto, se convirtió en la clave de la tabla <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>.</p>
<p>La forma moderna se lee por filas horizontales, los <strong>periodos</strong>: el primero contiene dos elementos, y los siguientes ochos, ocho, dieciocho, dieciocho y treinta y dos <span class="citation" data-cites="pauling1988 atkins2015">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>; <a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 2</a>)</span>. Esa secuencia 2, 8, 8, 18, 18, 32 corresponde al orden de llenado de las subcapas: los periodos cortos completan s y p, los largos añaden la d, y el más largo incorpora además la f <span class="citation" data-cites="pauling1988 atkins2015">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>; <a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 2</a>)</span>.</p>
<p>El patrón revela por qué la capacidad 2n² no se cumple: la capa n = 3 podría albergar dieciocho electrones, pero el potasio y el calcio rellenan la 4s antes que la 3d, de modo que el tercer periodo se corta en ocho y el cuarto se alarga hasta dieciocho <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>. Por eso los gases nobles ocupan los números atómicos 2, 10, 18, 36, 54 y 86, y no los que daría una mera cuenta de 2, 10 y 28 electrones por capa <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>.</p>
<p>Las columnas verticales reciben el nombre de <strong>grupos</strong>, y los elementos de un mismo grupo se llaman <strong>congéneres</strong>, porque comparten la configuración de la capa exterior y por ello sus propiedades físicas y químicas están estrechamente relacionadas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. El hidrógeno encabeza el grupo 1A aunque no es un metal, y el bloque central de transición rompe la uniformidad de las columnas largas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>.</p>
<p>Salvo el helio, todo gas noble presenta un <strong>octeto</strong>, ocho electrones exteriores con distribución ns²np⁶, y ese arreglo define la frontera química de la tabla <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. Representar el electrón de valencia mediante los <strong>símbolos de punto de Lewis</strong>, un punto por electrón alrededor del símbolo del elemento, permite visualizar de un vistazo el parentesco de un grupo entero <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>.</p>
<p>La posición en la tabla es entonces un resumen visual de la configuración: periodos y grupos codifican el número cuántico principal y la cantidad de electrones de valencia, las dos piezas que el capítulo 6 dedujo de los espectros <span class="citation" data-cites="atkins2015 pauling1988">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 2</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. Resta cuantificar cómo la carga nuclear llega filtrada hasta el electrón de valencia, primer eslabón de todas las propiedades periódicas que siguen <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
</section>
<section id="carga-nuclear-efectiva" class="level2">
<h2 class="anchored" data-anchor-id="carga-nuclear-efectiva">Carga nuclear efectiva</h2>
<p>La fuerza electrostática entre el núcleo y cada electrón depende de la carga neta que el electrón percibe, no de la carga total del núcleo: los demás electrones se interponen y blindan parcialmente esa carga <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. La <strong>carga nuclear efectiva</strong>, Zeff, es esa carga neta, y se define como la diferencia entre el número atómico Z y la <strong>constante de apantallamiento</strong> S, que mide cuánta carga nuclear ocultan los electrones internos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>:</p>
<p><span id="eq-zeff"><span class="math display">\[Z_{eff} = Z - S \tag{8.1}\]</span></span></p>
<p>En la ecuación <a href="#eq-zeff" class="quarto-xref">Ecuación&nbsp;<span>8.1</span></a>, Z cuenta los protones del núcleo y no tiene unidades; S expresa, en unidades de carga electrónica, la porción de carga nuclear que los electrones internos ocultan al electrón de valencia; su diferencia Zeff es la carga neta que gobierna la atracción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. En los límites, S = 0 recupera el átomo hidrogenoide, y si S = Z − 1, la carga neta queda reducida a una sola unidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>El sodio ofrece la primera lección: su núcleo tiene once protones y el core de neón cuenta diez electrones, con lo que cabría esperar Zeff = 1+, pero la carga neta real resulta ser 2,5+ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. La diferencia surge porque el electrón 3s penetra en el core, como se demostró en el capítulo 6, y entonces ve una fracción mayor del núcleo que la que el core prometía ocultarle <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>.</p>
<p>A lo largo de un periodo, Zeff del electrón de valencia crece regularmente: el litio percibe 1,3+, el sodio 2,5+ y el potasio 3,5+, porque cada nuevo protón añade carga que los electrones del mismo nivel apenas compensan entre sí <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. Hacia abajo de un grupo la subida es mucho más modesta, ya que los electrones interiores, más difusos, blindan menos de lo que cabría esperar <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>Cuando se quiere estimar S sin espectros, se emplean las <strong>reglas de Slater</strong>: contribuyen 0,00 los electrones de capas más externas, 0,35 los del mismo nivel, 0,85 los de la capa inmediatamente interior y 1,00 los más profundos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. En el flúor, cuyos siete electrones de valencia ocupan el nivel 2, la cuenta da S = 6 × 0,35 + 2 × 0,85 = 3,8 y Zeff = 9 − 3,8 = 5,2+, el valor que cita Brown <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>Pauling mide S por la vía espectral, no con reglas de Slater: despeja la carga efectiva de las propias energías de ionización, usando la energía de un átomo hidrogenoide con la que el capítulo 6 ya trabajó, y la fórmula resultante liga I con Zeff y con n <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>:</p>
<p><span id="eq-ionizacion-hidrogenoide"><span class="math display">\[I = \frac{(Z - S)^2}{n^2}\times 13{,}60\ \mathrm{eV} \tag{8.2}\]</span></span></p>
<p>En la ecuación <a href="#eq-ionizacion-hidrogenoide" class="quarto-xref">Ecuación&nbsp;<span>8.2</span></a>, I es la energía de ionización, medida en electronvoltios; Z − S es la carga nuclear efectiva de la ecuación <a href="#eq-zeff" class="quarto-xref">Ecuación&nbsp;<span>8.1</span></a>, elevada al cuadrado porque gobierna a la vez la atracción y la extensión del orbital; y n es el número cuántico principal de la capa del electrón <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>El factor 13,60 eV es la energía de ionización del hidrógeno, la constante que el capítulo 6 dedujo con el modelo de Bohr <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. En los límites, un n creciente reduce la energía hasta casi anularla para electrones lejanos, y S = 0 recupera el valor hidrogenoide exacto <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>La aplicación al litio muestra la potencia del método: con I₁ = 5,390 eV y n = 2, la ecuación <a href="#eq-ionizacion-hidrogenoide" class="quarto-xref">Ecuación&nbsp;<span>8.2</span></a> deja S = 1,74, lo que equivale a que cada electrón 1s blinda con una eficacia del 87 por ciento <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. La discrepancia con Brown, que reporta 1,3+, no es un error: un autor estima con reglas de Slater y el otro deduce del espectro <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Ambos coinciden en lo esencial, que la carga neta del litio supera apenas la unidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>La penetración, vista en el capítulo 6, se cuantifica con el mismo cálculo: para el litio, el electrón 2s da S = 1,74, mientras uno 2p daría 1,98, porque el primero pasa el 13 por ciento de su tiempo cerca del núcleo y el segundo apenas el 1 por ciento <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>. Esa diferencia ordena los orbitales de un mismo nivel en la secuencia s &lt; p &lt; d &lt; f <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span> y explica que, dentro de un nivel, se llene primero s y después p <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>La carga nuclear efectiva explica también el salto de las energías de ionización sucesivas: en el silicio, el quinto electrón arrancado vale 16 091 kJ/mol porque pertenece a la subcapa 2p y percibe una Zeff mucho mayor que la que percibían los cuatro electrones del nivel 3 que salieron antes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Ese número anticipa la tercera propiedad periódica, que examinamos después de los radios <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
</section>
<section id="radios-atómicos-y-radios-iónicos" class="level2">
<h2 class="anchored" data-anchor-id="radios-atómicos-y-radios-iónicos">Radios atómicos y radios iónicos</h2>
<p>Un átomo no tiene frontera definida, y por eso el tamaño se define operativamente: el <strong>radio de van der Waals</strong> es la mitad de la distancia mínima de acercamiento entre los núcleos de dos átomos no enlazados que colisionan, como se mide en los gases nobles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. El <strong>radio atómico de enlace</strong>, en cambio, es la mitad de la distancia entre los núcleos de dos átomos unidos por un enlace químico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Ambas escalas describen tamaños distintos y conviene no confundirlas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>Del radio de enlace hay valores medidos: en el yodo molecular, cuyos núcleos distan 2,66 Å, cada átomo contribuye 1,33 Å, y en el diamante, con 1,54 Å entre carbonos, la mitad da 0,77 Å <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Los gases nobles no forman enlaces propios y sus radios se estiman por otros caminos, como las distancias de colisión del argón <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>El radio de enlace sigue dos tendencias: crece hacia abajo en un grupo, porque cada periodo añade una capa completa de electrones, y decrece a lo largo de un periodo, porque la carga nuclear efectiva, cada vez mayor, atrae con más fuerza la nube de valencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>Cuando ambas tendencias compiten, como en la diagonal hacia abajo y a la derecha, los números muestran cuál domina: el fósforo, con 1,06 Å, es mayor que el azufre, de 1,02 Å, y el arsénico, de 1,19 Å, mayor que el selenio, de 1,16 Å <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. En cada par la capa nueva vence a la carga creciente, y en los elementos de transición la caída es menos regular, porque los electrones d se agregan en el interior <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>Los compuestos iónicos aportan la tercera escala: el <strong>radio iónico</strong> se calcula repartiendo la distancia entre cationes y aniones en un cristal, de modo que depende del arreglo cristalino y del número de coordinación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Aun así, los tamaños obtenidos son sistemáticos: el catión es siempre menor que su átomo neutro, y el anión siempre mayor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>La razón es electrónica: al perder electrones, el catión pierde los orbitales más extendidos y las repulsiones se relajan, mientras que al ganarlos, el anión añade carga que expande la nube <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Dentro del grupo, cationes y aniones de igual carga crecen hacia abajo con el número de capas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Pauling cuantifica el caso extremo del litio: el átomo neutro mide 1,68 Å y el catión Li⁺ apenas 0,22 Å, casi ocho veces menos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>.</p>
<p>La comparación de iones con el mismo número de electrones es especialmente limpia: en una <strong>serie isoelectrónica</strong> como O²⁻, F⁻, Na⁺, Mg²⁺ y Al³⁺, todos con diez electrones, el radio decrece al crecer la carga nuclear, porque la misma nube es atraída por núcleos cada vez más cargados <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Otra serie del mismo tipo, S²⁻, Cl⁻, K⁺ y Ca²⁺, con dieciocho electrones, reproduce la pauta con todos los radios mayores <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>El pequeño radio iónico del litio tiene consecuencias tecnológicas: las baterías de ion litio funcionan porque el diminuto Li⁺ se desliza entre las capas de grafito del ánodo y regresa al cátodo de LiCoO₂ durante la descarga, en la que el cobalto cambia su estado de oxidación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. El tamaño, y no solo la carga, decide así qué iones caben en los materiales del electrodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>Los radios preparan el resto del capítulo: el tamaño decide si un ion encaja en un sitio cristalino, cuánta energía libera una reacción y si un óxido se comporta como básico o ácido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. La siguiente propiedad, la energía de ionización, mide directamente la fortaleza con que el átomo retiene ese electrón de valencia cuyo tamaño acabamos de recorrer <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
</section>
<section id="energía-de-ionización" class="level2">
<h2 class="anchored" data-anchor-id="energía-de-ionización">Energía de ionización</h2>
<p>La energía de ionización del capítulo 6 mide la resistencia de un átomo a perder electrones: I₁ es la mínima para arrancar el primer electrón de un átomo gaseoso, e I₂ la del segundo, que se extrae del catión recién formado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Pauling tabula esas energías en electronvoltios por átomo y en kilojulios por mol, dos escalas que este capítulo alterna según convenga a cada valor <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>Las <strong>energías de ionización sucesivas</strong> del aluminio muestran de un solo vistazo la estructura de capas, desde los 5,984 eV del primer electrón hasta los 2298 eV del último, un recorrido de cerca de cuatrocientas veces que Pauling tabula para los trece electrones del elemento y que este capítulo reproduce en la tabla siguiente <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>:</p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Electrón</th>
<th>Energía (eV)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>5,984</td>
</tr>
<tr class="even">
<td>2</td>
<td>18,823</td>
</tr>
<tr class="odd">
<td>3</td>
<td>28,44</td>
</tr>
<tr class="even">
<td>4</td>
<td>119,96</td>
</tr>
<tr class="odd">
<td>5</td>
<td>153,77</td>
</tr>
<tr class="even">
<td>6</td>
<td>190,92</td>
</tr>
<tr class="odd">
<td>7</td>
<td>241,38</td>
</tr>
<tr class="even">
<td>8</td>
<td>284,53</td>
</tr>
<tr class="odd">
<td>9</td>
<td>330,1</td>
</tr>
<tr class="even">
<td>10</td>
<td>398,5</td>
</tr>
<tr class="odd">
<td>11</td>
<td>441,9</td>
</tr>
<tr class="even">
<td>12</td>
<td>2085</td>
</tr>
<tr class="odd">
<td>13</td>
<td>2298</td>
</tr>
</tbody>
</table>
</div>
<p>Entre la tercera energía, 28,44 eV, y la cuarta, 119,96 eV, media un salto de más de cuatro veces, y entre la undécima, 441,9 eV, y la duodécima, 2085 eV, otro de casi cinco <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Cada salto marca la frontera de una capa: los tres primeros electrones salen del nivel 3, los ocho siguientes de los niveles 2 y los dos últimos del nivel 1, en el orden que las reglas del capítulo 6 establecen <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>La tendencia principal es clara: I₁ crece de izquierda a derecha en cada periodo, porque la carga nuclear efectiva hace lo mismo, y decrece al bajar en un grupo, porque la capa de valencia se aleja del núcleo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. El mínimo de cada periodo lo marcan los metales alcalinos y el máximo los gases nobles, y el helio encabeza toda la tabla con 24,58 eV <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>Pauling resume la pendiente de otra manera: I₁ crece hasta el gas noble y luego cae a menos de la cuarta parte para el metal alcalino que inaugura el periodo siguiente, del helio, con 24,58 eV, al litio, con 5,390 eV <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Esa caída brusca es la firma electrónica de un nuevo nivel que se abre <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Brown ilustra la misma caída en sus gráficas de la energía de ionización frente al número atómico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>La tendencia general tiene excepciones sistemáticas que la configuración explica: entre berilio y boro la energía desciende, porque el electrón nuevo entra en una subcapa 2p de mayor energía que la 2s, y entre nitrógeno y oxígeno también, porque el cuarto electrón p debe aparearse y la repulsión lo debilita <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Ambas son consecuencias directas del orden de llenado y de la regla de Hund del capítulo 6 <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–3</a>)</span>.</p>
<p>En los elementos de transición las energías de ionización caen en una banda estrecha, porque el electrón arrancado sale de una subcapa d interior, protegida por la valencia exterior, y en el bloque f la banda es aún menor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Los representativos, en cambio, barren cada periodo un rango amplio, del orden de 4 a 5 eV de un alcalino a varias veces más de su gas noble vecino <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Esa escala separa los metales, que pierden, de los no metales, que ganan <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>Las energías sucesivas explican también la configuración que adoptan los iones: primero salen los electrones de mayor n y, a n igual, los de mayor l; el hierro pierde así los dos 4s antes que los 3d, y el estaño los dos 5p antes que los 5s <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>Que el 4s se haya llenado antes no lo protege: al ionizar no se añaden protones, y la energía decide entre capas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. Para los aniones, en cambio, se llena el orbital vacío de menor energía disponible, una decisión que este capítulo retoma al escribir las configuraciones de los iones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>Tres configuraciones de iones ilustran la regla: el galio, de configuración [Ar]3d¹⁰4s²4p¹, forma Ga³⁺ quedándose [Ar]3d¹⁰, tras ceder el 4p y los dos 4s; el cromo trivalente, Cr³⁺, pierde el 4s y un 3d y deja [Ar]3d³ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.7)</span>. El anión bromuro, por su parte, cierra la subcapa 4p con un electrón y alcanza la configuración del criptón, [Kr] <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.7)</span>. Los tres casos comparten la meta: la configuración del gas noble más cercano <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>La energía de ionización, junto con la afinidad electrónica, decide de qué lado de la valencia se sitúa cada elemento, pero conviene subrayar la asimetría: ionizar un átomo exige energía en todos los casos, mientras que añadir un electrón puede liberarla o absorberla según el elemento <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.5</a>)</span>. Esa segunda propiedad es la siguiente parada del capítulo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>.</p>
</section>
<section id="afinidad-electrónica" class="level2">
<h2 class="anchored" data-anchor-id="afinidad-electrónica">Afinidad electrónica</h2>
<p>La <strong>afinidad electrónica</strong> es la variación de entalpía que acompaña la adición de un electrón a un átomo gaseoso, y se reporta con el signo de la química: negativa cuando el proceso libera energía <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. El cloro, con −349 kJ/mol, es el ejemplo extremo: ganar el electrón completa su subcapa 3p y produce el cloruro con configuración de argón <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. La afinidad electrónica es el espejo de la energía de ionización, la facilidad con que un átomo acepta carga <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>.</p>
<p>Los halógenos dominan la tabla de afinidades porque les falta un solo electrón para el octeto: flúor, cloro, bromo y yodo liberan energía al capturarlo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. En el extremo opuesto, los gases nobles y los metales alcalinotérreos muestran afinidades positivas o poco negativas: el argón, por ejemplo, no forma un anión estable porque el electrón añadido ocuparía una subcapa nueva <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. Los elementos del grupo 5A, cuya subcapa p queda semillena, tienen también afinidades menos negativas que sus vecinos de la izquierda <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>.</p>
<p>La afinidad varía poco al descender en un grupo, menos de lo que cabría esperar: al crecer la distancia, la atracción del núcleo por el electrón entrante disminuye, pero también lo hace la repulsión entre electrones, y ambos efectos casi se anulan <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. Por eso, sorprendentemente, el flúor tiene una afinidad menos negativa que el cloro, una anomalía que Pauling destaca como notable <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 6–8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>.</p>
<p>Pauling añade números que Brown no reporta: para los no metales, la afinidad del primer electrón ronda los 350 kJ/mol, el oxígeno captura el primero con apenas 140 kJ/mol, y el segundo electrón prácticamente no se incorpora, de modo que el ion O²⁻ libre no se forma en fase gaseosa y su energía se compensa solo en la red de los óxidos iónicos <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 6–8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Los dos autores convergen en el fondo: el doble anión de oxígeno no existe como especie gaseosa aislada <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 6–8</a>)</span>.</p>
<p>Juntas, la energía de ionización y la afinidad electrónica delimitan el territorio de la valencia: los metales alcalinos entregan su electrón con energías del orden de 4 a 5 eV, los halógenos lo capturan liberando unos 3,5 eV, y esa brecha de electronvoltios separa a los donantes de los aceptores de electrones <span class="citation" data-cites="pauling1988 pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">1988, sec. 6–8</a>)</span>. Sobre esa brecha se construye el carácter metálico, la última propiedad del recorrido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
</section>
<section id="carácter-metálico-metales-no-metales-y-metaloides" class="level2">
<h2 class="anchored" data-anchor-id="carácter-metálico-metales-no-metales-y-metaloides">Carácter metálico: metales, no metales y metaloides</h2>
<p>El <strong>carácter metálico</strong> resume en una palabra la conducta que la energía de ionización y la afinidad electrónica predicen: tienden a ceder electrones los metales y a ganarlos los no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. En la tabla, la metalicidad crece hacia abajo dentro de cada grupo y decrece de izquierda a derecha dentro de cada periodo, siguiendo a la energía de ionización <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Esa doble tendencia traza la frontera diagonal que separa los dos grandes campos del sistema periódico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Los metales son lustrosos cuando se cortan, buenos conductores del calor y de la electricidad, maleables y dúctiles, con la banda de valencia parcialmente ocupada <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Todos son sólidos a 25 °C salvo el mercurio, que funde a −39 °C; entre los blandos destacan el cesio, a 28,4 °C, y el galio, a 29,8 °C, mientras el cromo aguanta hasta 1900 °C y el diamante, pese a no ser metal, hasta 3570 °C <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Cuando un metal se combina con un no metal, los electrones se transfieren: el óxido de níquel, por ejemplo, resulta de ceder el níquel dos electrones al oxígeno, con lo que quedan los iones Ni²⁺ y O²⁻ en un sólido iónico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Los compuestos iónicos son duros, quebradizos y de punto de fusión alto, y fundidos conducen la corriente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Los óxidos de los metales son <strong>óxidos básicos</strong>: los solubles reaccionan con el agua para dar hidróxidos, y los insolubles, como el NiO, se disuelven en los ácidos formando una sal y agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Esa química hereda la neutralización del capítulo 5 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. El óxido de escandio, Sc₂O₃, es un ejemplo extremo: funde a 2485 °C y reacciona con el ácido nítrico para dar nitrato de escandio y agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.8)</span>.</p>
<p>Los no metales son lo contrario: sin brillo, malos conductores y quebradizos, pueden ser gases, líquidos o sólidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Solo siete elementos forman moléculas diatómicas en condiciones ordinarias: cinco gases, el H₂, el N₂, el O₂, el F₂ y el Cl₂; un líquido, el Br₂, y un sólido volátil, el I₂ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Los no metales tienden a ganar electrones, y su reacción con un metal produce compuestos iónicos como el bromuro de aluminio, AlBr₃ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Los compuestos de los no metales entre sí son moleculares y de bajos puntos de ebullición, como el metano, el propano, el octano o el amoníaco, y muchos fármacos, como el celecoxib de fórmula C₁₇H₁₄F₃N₃O₂S, son moléculas de no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Su química se resume en los <strong>óxidos ácidos</strong>: el CO₂ disuelto produce ácido carbónico en la lluvia y en las bebidas carbonatadas, y el SO₂ y el SO₃ de la quema de combustibles fósiles forman la lluvia ácida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>El dióxido de selenio ofrece el ejemplo cuantitativo: disuelto en agua, el SeO₂ se combina con ella para dar ácido selenioso, y ese ácido reacciona con el hidróxido de sodio para dar una sal y agua, la doble reacción que define a los óxidos ácidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.9)</span>. La misma pareja de reacciones, con el agua y con la base, distingue en la práctica a un óxido básico de uno ácido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Entre ambos campos se sitúan los metaloides ya presentados en el capítulo 6, con propiedades intermedias y conductividad que crece con la temperatura, al revés que en los metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. El teluro, por ejemplo, se clasifica como metaloide pese a bordear el grupo 6A de los no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El silicio, el más célebre, es un <strong>semiconductor</strong> cuya conductividad se controla con impurezas llamadas <strong>dopantes</strong> <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>La frontera metal-no metal no es una línea dura: la metalicidad es un gradiente, y la misma posición que separa los óxidos básicos de los ácidos decide el comportamiento de cada compuesto binario <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Con el mapa general trazado, conviene recorrer ahora dos territorios concretos, los grupos de los metales más reactivos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
</section>
<section id="tendencias-en-los-grupos-1a-y-2a" class="level2">
<h2 class="anchored" data-anchor-id="tendencias-en-los-grupos-1a-y-2a">Tendencias en los grupos 1A y 2A</h2>
<p>Los <strong>metales alcalinos</strong> del grupo 1A son blandos, plateados y de baja densidad, y deben su nombre a la palabra árabe que designa las cenizas de las que se extrajeron las primeras lejías <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Su punto de fusión desciende y su densidad sube regularmente del litio al cesio, con la reactividad creciendo en el mismo sentido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Con la energía de ionización más baja de su periodo, cada alcalino pierde el electrón s exterior con facilidad y forma el catión M⁺ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. En la naturaleza solo aparecen así, oxidados: el sodio y el potasio abundan en la corteza, en el agua de mar y en los fluidos biológicos, y el litio brilla en las baterías que recorrimos en la sección de radios <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.3</a>)</span>. Su química consiste en devolver ese electrón <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Con el hidrógeno forman los <strong>hidruros</strong>, compuestos en los que el hidrógeno actúa como <strong>ion hidruro</strong> H⁻, con la configuración del helio, y con el azufre y los halógenos dan sulfuros y halogenuros, siempre con el metal en el estado de oxidación +1 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. El contraste con el hidrógeno de los ácidos, que en el capítulo 5 cedía su electrón al agua, muestra lo flexible que resulta este elemento según el compañero <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.8</a>)</span>.</p>
<p>Con el agua, la reacción es tan exotérmica que puede inflamar el hidrógeno que desprende y exige precaución: dos moles de metal producen dos de hidróxido y uno de H₂ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. La violencia crece hacia abajo del grupo, del litio, que apenas chisporrotea, al cesio, que puede explotar, porque la energía de ionización decrece y cada reacción libera más calor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Con el oxígeno, el producto depende del metal: el litio da el óxido Li₂O, con el ion O²⁻; el sodio y sus vecinos forman además <strong>peróxidos</strong>, con el ion O₂²⁻, y potasio, rubidio y cesio alcanzan los <strong>superóxidos</strong>, con el ion O₂⁻ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Por su reactividad, los alcalinos se conservan sumergidos en kerosene o en aceite mineral, fuera del aire y de la humedad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Aunque sus iones son incoloros, los alcalinos tiñen la llama: el sodio emite el amarillo de 589 nanómetros que domina las lámparas de vapor de sodio de carreteras y estadios <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Esta emisión retoma los espectros del capítulo 6: cada catión libera la energía de su electrón de valencia en cuantos característicos <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 6.3</a>)</span>. El cesio es el alcalino estable más reactivo, y el francio, radiactivo y efímero, no se estudia en el laboratorio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>El cesio protagoniza el ejemplo tipológico del grupo: con el cloro da cloruro de cesio, con el agua hidróxido e hidrógeno y con el hidrógeno hidruro de cesio, las tres reacciones con el metal en el estado +1 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.10)</span>. La misma tríada de reacciones se repite, con violencia decreciente, en todo el grupo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Los <strong>metales alcalinotérreos</strong> del grupo 2A, en cambio, exigen ceder dos electrones, y su química se modera <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Los alcalinotérreos son más duros, más densos y de punto de fusión más alto que sus vecinos del grupo 1A, porque cada átomo aporta dos electrones de enlace <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Su energía de ionización, baja pero mayor que la de los alcalinos, los vuelve menos reactivos, y dentro del grupo la reactividad crece del berilio al bario <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. El magnesio y el calcio abundan en el mar y en los minerales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Con el agua la gradación se hace visible: el berilio no reacciona ni siquiera con el vapor al rojo, el magnesio lo hace despacio con el agua líquida y deprisa con el vapor, y el calcio y sus compañeros reaccionan a temperatura ambiente, aunque con menos violencia que los alcalinos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. El magnesio arde con un resplandor blanco intenso y su óxido forma una capa protectora, por lo que sus aleaciones ligeras sirven para ruedas de automóvil y carcasas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>El estroncio se asocia al rojo de los fuegos artificiales y el bario a su verde, y el calcio es indispensable en huesos y dientes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Todos los alcalinotérreos forman compuestos iónicos con aniones divalentes, como el carbonato que el capítulo 5 estudió en las rocas y en el agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. Con estos dos grupos queda claro el patrón: dentro de una columna, la energía de ionización y el radio se mueven juntos para regular la reactividad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Los hidruros, los óxidos y las reacciones con agua de los grupos 1A y 2A ilustran el poder predictivo de la tabla, pero la mitad derecha del sistema guarda todavía sus propias familias <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. El recorrido por los no metales que sigue completa el cuadro con el hidrógeno, el oxígeno, el azufre, los halógenos y los gases nobles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
</section>
<section id="no-metales-seleccionados" class="level2">
<h2 class="anchored" data-anchor-id="no-metales-seleccionados">No metales seleccionados</h2>
<p>El hidrógeno abre la lista con una anomalía: aunque ocupa el grupo 1A, no es un metal, y en condiciones ordinarias es un gas incoloro de moléculas diatómicas H₂ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Su energía de ionización, de 1312 kJ/mol, más del doble que la de cualquier alcalino, lo acerca a los no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Por eso comparte con el oxígeno y el cloro, más que cede como los alcalinos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>Con los metales activos da hidruros con el ion H⁻, como los del grupo 1A, y esa doble personalidad lo convierte en un elemento aparte, colocado a menudo sobre los alcalinos solo por conveniencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. En disolución acuosa, su protagonismo regresa al ion H⁺ de los ácidos que el capítulo 5 dejó preparado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>En el grupo 6A desciende la metalicidad: oxígeno, azufre y selenio son no metales, el teluro es metaloide y el polonio, radiactivo y raro, ya es un metal <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El oxígeno, el más abundante de la corteza, existe como dos <strong>alótropos</strong>, formas del mismo elemento en el mismo estado físico: el dioxígeno O₂, que respiramos, y el <strong>ozono</strong> O₃ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Llamar dioxígeno al primero evita la ambigüedad con el elemento <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>El ozono se forma en las descargas eléctricas y absorbe la radiación ultravioleta que el O₂ deja pasar, por lo que en la estratosfera es protector, mientras que a ras de suelo, en el aire contaminado, es un oxidante dañino <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Su formación, endotérmica, lo hace menos estable que el dioxígeno, y esa inestabilidad es la fuente de su poder oxidante <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El oxígeno llega a la configuración del neón ganando dos electrones, el ion O²⁻ del que dependen los óxidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>El azufre, sólido amarillo, se presenta como anillos de ocho átomos, S₈, y se escribe S(s) por simplicidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Con los metales forma sulfuros con el ion S²⁻, y la mayor parte del azufre natural vive en esos minerales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Al quemar carbón y petróleo, el azufre escapa como dióxido SO₂, un contaminante que este capítulo asoció con la lluvia ácida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>El selenio, esencial en trazas y tóxico en exceso, adopta también anillos de ocho como el azufre, mientras el teluro prefiere cadenas retorcidas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Su química es la del anión −2, y sus hidruros muestran la estabilidad decreciente con el tamaño: el agua es la más estable de la serie H₂O, H₂S, H₂Se y H₂Te <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. La tabla predice así, sin experimento, cuál de los cuatro sobrevive al calor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>Los <strong>halógenos</strong> del grupo 7A pasan del gas al sólido al descender: el flúor y el cloro son gases, el bromo líquido y el yodo un sólido lustroso y volátil, con puntos de fusión y ebullición crecientes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Todos forman moléculas diatómicas X₂, y a todos les falta un electrón para el octeto, la razón de sus afinidades tan negativas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Su química consiste en capturar ese electrón y formar el ion halogenuro X⁻ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>La reactividad decrece hacia abajo: el flúor, el oxidante más potente conocido, arranca electrones incluso del agua, con una reacción tan exotérmica que obliga a manejarlo con equipo especial <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El cloro, con todo, es el halógeno de mayor uso industrial: solo en 2008, Estados Unidos produjo unos 21 000 millones de libras, entre los diez principales productos químicos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Con el agua reacciona dando los ácidos clorhídrico e hipocloroso, el dúo desinfectante de piscinas y de agua potable <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>Con los metales, los halógenos dan halogenuros iónicos, y con el hidrógeno, halogenuros de hidrógeno gaseosos que, disueltos, forman los hidrácidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Entre ellos, el clorhídrico, el bromhídrico y el yodhídrico son ácidos fuertes, pero el fluorhídrico es débil, otra desviación que la tabla no anticipa y que el libro retomará al estudiar los ácidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>Los <strong>gases nobles</strong> cierran el recorrido: monoatómicos, incoloros e inodoros, con las subcapas s y p llenas y las energías de ionización más altas de sus periodos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Esa inercia les valió el nombre de inertes, y su química pareció cerrada para siempre <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El cierre duró hasta 1962, cuando Bartlett, en la Universidad de Columbia Británica, preparó el primer compuesto de xenón <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>Pauling ya lo había anunciado: en 1932 sugirió que los gases nobles debían ser capaces de formar compuestos con el flúor, el elemento más reactivo del sistema, y su predicción cayó en el olvido hasta que Bartlett la confirmó en 1962, con la síntesis del primer compuesto de xenón <span class="citation" data-cites="brock2015 brown2012">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>El xenón reacciona con el hexafluoruro de platino para dar XePtF₆, y con el flúor elemental forma los fluoruros XeF₂, XeF₄ y XeF₆ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. El kriptón apenas alcanza el difluoruro KrF₂, el helio y el neón no reaccionan con nada, y en 2000 un equipo finlandés logró el fluorhidruro de argón, HArF, estable solo a temperaturas muy bajas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
<p>El grupo 8A ilustra con nitidez cómo las propiedades periódicas se leen en la posición: la energía de ionización cae al descender, y ese gradiente basta para explicar por qué solo los gases nobles pesados entran en la química de la valencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Con las familias del sistema recorridas, queda integrar las cinco propiedades en un solo elemento, como hace el ejemplo que cierra el capítulo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
</section>
<section id="ejemplo-resuelto-el-bismuto-miembro-pesado-del-grupo-5a" class="level2">
<h2 class="anchored" data-anchor-id="ejemplo-resuelto-el-bismuto-miembro-pesado-del-grupo-5a">Ejemplo resuelto: el bismuto, miembro pesado del grupo 5A</h2>
<p>El subsalicilato de bismuto es el ingrediente activo de Pepto-Bismol, un remedio de venta libre contra las molestias gástricas, y su metal sirve de hilo conductor para integrar las cinco propiedades del capítulo en un solo elemento <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. El bismuto, de número atómico 83, es el miembro más pesado del grupo 5A, junto al nitrógeno, el fósforo, el arsénico y el antimonio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
<p>La primera pregunta pide predecir el radio del bismuto: en el sexto periodo los radios de enlace del talio, 1,48 Å, y del plomo, 1,47 Å, apenas difieren entre sí, de modo que el bismuto debe medir alrededor de 1,45 Å <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. El valor tabulado, 1,46 Å, confirma la estimación y muestra que en la parte baja de un periodo los radios se comprimen muy poco <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
<p>Su carácter metálico se decide por la posición: aunque el grupo 5A empieza con no metales, la metalicidad crece hacia abajo, y el bismuto, quinto miembro, es ya un metal <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. Su energía de ionización baja y su tendencia a ceder electrones lo acercan al plomo y al talio, sus vecinos metálicos del sexto periodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. Esa lectura explica, sin experimento, que el bismuto forme compuestos iónicos con los no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
<p>Como metal, el bismuto forma un óxido básico, el Bi₂O₃, que reacciona con los ácidos: con el nítrico diluido da nitrato de bismuto y agua, y un mol de óxido consume seis de ácido y entrega dos de nitrato, Bi₂O₃ + 6 HNO₃ → 2 Bi(NO₃)₃ + 3 H₂O <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. Esta reacción es la huella de los óxidos básicos que la sección sobre el carácter metálico describió <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>La estequiometría cierra el círculo: si 6,77 g de Bi₂O₃ se disuelven para formar 0,500 litros de disolución, la masa molar del óxido vale 466 g por mol, tomando el bismuto igual a su número másico 209 y el oxígeno igual a 16,00, como se hizo en el capítulo 4 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
<p>Los moles valen 6,77 entre 466, unos 1,45 × 10⁻², y como cada mol de óxido da dos de Bi³⁺, la concentración del ion resulta 2,91 × 10⁻² entre 0,500, unas 5,8 × 10⁻² moles por litro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. Todos los números proceden del problema o de las masas del capítulo 4 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
<p>La masa atómica usada no es casual: el bismuto tiene un solo isótopo estable, el ²⁰⁹Bi, con 83 protones y 126 neutrones, el más pesado de todos los isótopos estables <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. Un cubo del metal de 5,00 cm de arista, con densidad 9,808 gramos por centímetro cúbico, pesa 1226 g y contiene unos 5,87 moles, es decir, unas 3,53 × 10²⁴ unidades de átomos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>. El ejemplo entero muestra cómo se encadenan las cinco propiedades periódicas y la aritmética química del capítulo 4 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
</section>
<section id="preguntas-y-ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="preguntas-y-ejercicios">Preguntas y ejercicios</h2>
<p>Los ejercicios que siguen están inspirados en la tipología de <span class="citation" data-cites="brown2012">Brown et&nbsp;al. (<a href="../references.html#ref-brown2012" role="doc-biblioref">2012</a>)</span> (cap. 7) y <span class="citation" data-cites="pauling1988">Pauling (<a href="../references.html#ref-pauling1988" role="doc-biblioref">1988</a>)</span> (caps. 2 y 5); los valores numéricos citados proceden de las fuentes o se derivan de ellas mediante las reglas del capítulo, sin introducir datos ajenos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 7</a>)</span>. Cada cuestión puede resolverse con los conceptos ya expuestos y con los números que el propio enunciado aporta <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 7</a>)</span>.</p>
<p>Con las reglas de Slater, calcule la carga nuclear efectiva que percibe un electrón de valencia del oxígeno y compárela con la del flúor, de 5,2+; explique por qué la carga neta crece hacia la derecha del periodo aun cuando los electrones de valencia aumentan <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>Ordene de menor a mayor radio atómico de enlace los elementos sodio, magnesio, aluminio, azufre y cloro, todos del tercer periodo, y justifique el orden con la carga nuclear efectiva creciente y el número fijo de capas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Explique además por qué el radio no depende solo de la carga nuclear total, sino de la neta que percibe la valencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>El litio mide 1,68 Å y su catión 0,22 Å; calcule cuántas veces mayor es el átomo que el ion y relacione la diferencia con la pérdida de los orbitales más extendidos y con la relajación de las repulsiones <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. Indique además qué configuración conserva el catión y por qué esa configuración es tan compacta <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>.</p>
<p>Con la tabla de energías de ionización sucesivas del aluminio, identifique qué subcapa abandona cada electrón, explique el salto entre la tercera y la cuarta energía y diga cuánto cuesta arrancar el primer electrón 1s <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Compare además el coste de la valencia completa, que suma 53,2 eV, con el del primer electrón interior <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>El segundo electrón del sodio cuesta 4562 kJ/mol y el del calcio 1145 kJ/mol; explique la diferencia apelando a las configuraciones de los cationes y a la carga nuclear efectiva del core <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.5)</span>. Justifique por qué el sodio se conforma con perder un solo electrón mientras el calcio cede los dos con energías parecidas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.5)</span>.</p>
<p>El cloro libera 349 kJ/mol al ganar un electrón, el argón no forma anión estable y el flúor libera menos que el cloro; explique los tres hechos con la configuración electrónica y el balance entre atracción y repulsión <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 6–8</a>)</span>. Indique además qué configuración alcanza cada anión y por qué esa meta hace tan favorable la captura en los halógenos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>.</p>
<p>Un compuesto de fórmula ACl₃ funde a −112 °C; decida si es molecular o iónico y si A es el escandio o el fósforo, comparando además con el óxido de escandio, que funde a 2485 °C <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. Justifique la respuesta con el carácter metálico de A y con las propiedades de los compuestos iónicos frente a los moleculares <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
<p>Justifique con la energía de ionización por qué la reacción del cesio con el agua es más violenta que la del litio, y explique por qué el berilio no reacciona ni con el vapor de agua mientras el magnesio sí lo hace con facilidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>Escriba las configuraciones electrónicas de los iones Ga³⁺, Cr³⁺ y Br⁻ e indique qué electrón abandona el átomo neutro en el primer caso y qué orbital recibe el electrón en el último <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.7)</span>. Apoye cada respuesta en la regla de quitar primero los electrones de mayor n y de mayor l <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>Explique por qué el xenón forma compuestos con el flúor y el helio no, y qué papel desempeñó en ese descubrimiento la predicción de Pauling de 1932, tres décadas antes de la síntesis de Bartlett <span class="citation" data-cites="brown2012 brock2015">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>; <a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>)</span>. Relacione la respuesta con la tendencia de la energía de ionización dentro del grupo 8A <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
</section>
<section id="solucionario" class="level2">
<h2 class="anchored" data-anchor-id="solucionario">Solucionario</h2>
<p>Para el oxígeno, las reglas de Slater dan S = 5 × 0,35 + 2 × 0,85 = 3,45, de modo que Zeff = 8 − 3,45 ≈ 4,6+, algo menor que los 5,2+ del flúor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. La carga neta crece hacia la derecha porque cada nuevo protón supera el apantallamiento que aportan los electrones del mismo nivel, que apenas se protegen entre sí <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>.</p>
<p>En el tercer periodo todos los elementos del ejercicio comparten tres capas, y el radio queda gobernado por la carga nuclear efectiva, que crece con el número atómico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. El orden de menor a mayor es, por tanto, cloro, azufre, aluminio, magnesio y sodio, y el sodio, que solo percibe 2,5+, resulta el mayor del conjunto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>El cociente entre 1,68 Å y 0,22 Å da 7,6, es decir, el átomo de litio es casi ocho veces más grande que su catión <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>)</span>. La ionización despoja al litio de su único electrón 2s, el más externo y el menos atraído, y deja un core de helio con los dos electrones 1s muy juntos al núcleo y sin repulsiones externas que estiren la nube <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>.</p>
<p>El primer electrón del aluminio sale de la subcapa 3p y cuesta 5,984 eV; los dos siguientes, de la 3s, cuestan 18,823 y 28,44 eV; los seis de la 2p, de 119,96 a 330,1 eV; los dos de la 2s, 398,5 y 441,9 eV; y los de la 1s, 2085 y 2298 eV <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>El salto entre la tercera y la cuarta energía marca la entrada al core, donde la carga nuclear efectiva es mucho mayor, y el duodécimo electrón, ya de la capa 1, cuesta 2085 eV <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>. Este doble salto resume, en un solo elemento, el paisaje de capas que recorre toda la tabla periódica <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>El sodio pierde con facilidad su único electrón 3s y queda con la configuración del neón; el segundo electrón debe salir del core 2p, que percibe una carga nuclear mucho mayor, y por eso I₂ se dispara a 4562 kJ/mol <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.5)</span>. El calcio, en cambio, tiene dos electrones 4s en la misma capa, y los 1145 kJ/mol del segundo corresponden a un electrón de valencia, no de core <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.5)</span>.</p>
<p>El cloro completa con el electrón entrante la subcapa 3p y alcanza la configuración del argón, una meta tan favorable que el proceso libera 349 kJ/mol <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. El argón, con el octeto ya lleno, forzaría al electrón a una subcapa nueva y más alta, y el proceso absorbería energía; el flúor, más pequeño, sufre una repulsión entre electrones que resta algo del beneficio que el cloro, más espacioso, conserva <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 6–8</a>)</span>.</p>
<p>El punto de fusión de −112 °C revela fuerzas intermoleculares débiles y, por tanto, moléculas: el compuesto es el tricloruro de fósforo, PCl₃, del no metal fósforo, y no el cloruro de escandio, porque el escandio, metal, formaría con el cloro un sólido iónico de punto de fusión muy alto, como su óxido Sc₂O₃, que funde a 2485 °C <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.8)</span>.</p>
<p>La violencia de la reacción con el agua depende del calor liberado al formar el hidróxido y el hidrógeno: al bajar en el grupo 1A la energía de ionización decrece, la reacción se vuelve más exotérmica y el cesio, la más violenta <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. El berilio, con sus electrones 2s más atraídos por el núcleo, no reacciona ni con el vapor, mientras el magnesio, con electrones 3s más sueltos, alcanza la energía necesaria con el vapor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>.</p>
<p>El galio cede el 4p y los dos 4s y queda como [Ar]3d¹⁰; el cromo pierde el 4s y un 3d y deja [Ar]3d³; el bromo acepta un electrón en la 4p para cerrar el octeto y alcanza [Kr] <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Exercise 7.7)</span>. Los tres casos siguen la regla de sacrificar primero los electrones de mayor n y de llenar después los huecos de menor energía <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>.</p>
<p>El helio tiene la energía de ionización más alta de la tabla, y no hay oxidante capaz de arrancarle su par 1s, mientras el xenón, con la menor del grupo 8A, cede electrones al flúor y forma fluoruros <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. Pauling ya predijo en 1932 que los gases nobles debían reaccionar con el flúor, una sugerencia ignorada hasta que Bartlett, en 1962, obtuvo el primer compuesto de xenón <span class="citation" data-cites="brock2015 brown2012">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>.</p>
</section>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>La tabla periódica resume la configuración electrónica en dos ejes: el periodo añade una capa y el grupo fija el número de electrones de valencia, y esa doble codificación explica periodos de 2, 8, 8, 18, 18 y 32 elementos y el octeto de los gases nobles <span class="citation" data-cites="pauling1988 atkins2015">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>; <a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 2</a>)</span>. La ley periódica nació con Mendeleev y se impuso gracias a sus predicciones confirmadas, del galio al hafnio <span class="citation" data-cites="brock2015 pauling1988">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 5</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>
<p>Cinco propiedades periódicas gobiernan la química: la carga nuclear efectiva, que crece hacia la derecha y poco hacia abajo; el radio atómico e iónico, que se contrae al avanzar en el periodo y se expande al bajar en el grupo; la energía de ionización, que sube hacia la derecha y baja al descender; la afinidad electrónica, más negativa en los halógenos; y el carácter metálico, que sigue a la energía de ionización <span class="citation" data-cites="brown2012 brown2012 brown2012 brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.3</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.6</a>)</span>.</p>
<p>Las familias ilustran las tendencias: los alcalinos ceden su único electrón, los alcalinotérreos dos, los halógenos capturan uno y los gases nobles, salvo el xenón y el kriptón, no reaccionan <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.8</a>)</span>. La misma tabla que predice el radio del bismuto anticipa el tipo de óxido, la estequiometría del nitrato y la masa de un cubo del metal puro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012</a>, Sample Integrative Exercise)</span>.</p>
</section>
<section id="autoevaluación" class="level2">
<h2 class="anchored" data-anchor-id="autoevaluación">Autoevaluación</h2>
<p>Antes de avanzar, conviene verificar el dominio del capítulo: explique con sus propias palabras por qué la carga nuclear efectiva crece hacia la derecha y casi no al bajar, por qué los cationes son menores que sus átomos y los aniones mayores, y por qué la energía de ionización salta entre subcapas, usando el aluminio como ejemplo <span class="citation" data-cites="brown2012 brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.3</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–2</a>)</span>.</p>
<p>Compruebe también la lectura de tabla: dado el elemento de número atómico 34, ubíquelo en periodo y grupo, prediga si su óxido es básico o ácido y si su energía de ionización es mayor o menor que la del bromo, apoyándose en las tendencias del capítulo <span class="citation" data-cites="brown2012 brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">2012, sec. 7.6</a>)</span>. Relea los párrafos necesarios antes de pasar al estudio del enlace químico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>.</p>
</section>
<section id="enlace-al-próximo-capítulo" class="level2">
<h2 class="anchored" data-anchor-id="enlace-al-próximo-capítulo">Enlace al próximo capítulo</h2>
<p>La tabla periódica ha convertido las configuraciones del capítulo 6 en predicciones químicas, pero todavía falta la pieza que explica cómo se unen los átomos: los electrones de valencia que ceden los metales y capturan los no metales se organizan en enlaces <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 8.1</a>)</span>. El próximo capítulo estudia esa organización, desde los símbolos de punto de Lewis de este capítulo hasta los enlaces iónico y covalente, y la regla del octeto deja de ser una frase para convertirse en el motor del enlace químico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 8.1</a>)</span>.</p>
</section>
<section id="glosario-acumulativo" class="level2">
<h2 class="anchored" data-anchor-id="glosario-acumulativo">Glosario acumulativo</h2>
<p><strong>Ácido</strong>: sustancia que se ioniza en disolución acuosa para formar iones H⁺, por lo que se llama donador de protones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Ácido débil</strong>: ácido parcialmente ionizado en disolución, electrolito débil <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Ácido fuerte</strong>: ácido completamente ionizado en disolución, electrolito fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Base</strong>: sustancia que acepta iones H⁺ y produce iones OH⁻ al disolverse en agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Base débil</strong>: base parcialmente ionizada en disolución, electrolito débil <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Base fuerte</strong>: base completamente ionizada en disolución, electrolito fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Concentración</strong>: cantidad de soluto disuelta en una cantidad dada de solvente o de disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.5</a>)</span>. <strong>De-electronación</strong>: término de Pauling para la oxidación, la pérdida de electrones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–3</a>)</span>. <strong>Dilución</strong>: proceso de añadir solvente a una disolución sin cambiar los moles de soluto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.5</a>)</span>. <strong>Disociación</strong>: separación de un compuesto iónico en sus iones al disolverse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Disolución estándar</strong>: disolución reactivo de concentración conocida usada en una valoración <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.6</a>)</span>. <strong>Disolución madre</strong>: disolución concentrada a partir de la cual se preparan otras más diluidas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.5</a>)</span>. <strong>Ecuación iónica completa</strong>: ecuación que muestra todos los electrolitos fuertes solubles como sus iones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Ecuación iónica neta</strong>: ecuación que incluye solo las especies directamente involucradas en la reacción, sin iones espectadores <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Ecuación molecular</strong>: ecuación que muestra las fórmulas químicas completas sin indicar el carácter iónico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Electronación</strong>: término de Pauling para la reducción, la ganancia de electrones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–3</a>)</span>. <strong>Electrolito</strong>: sustancia cuyas disoluciones acuosas contienen iones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Electrolito débil</strong>: soluto que existe en disolución sobre todo como moléculas neutras <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Electrolito fuerte</strong>: soluto que existe en disolución completa o casi completamente como iones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Indicador ácido-base</strong>: tinte que cambia de color al pasar el punto de equivalencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.6</a>)</span>. <strong>Iones espectadores</strong>: iones que aparecen en forma idéntica en ambos lados de la ecuación iónica completa y no participan en la reacción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Molaridad</strong>: número de moles de soluto en un litro de disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.5</a>)</span>. <strong>No electrolito</strong>: sustancia que no forma iones al disolverse en agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Número de oxidación</strong>: carga hipotética asignada a cada átomo al dividir artificialmente los electrones de un compuesto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Oxidación</strong>: pérdida de electrones por una sustancia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Precipitado</strong>: sólido insoluble formado por una reacción en disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Punto de equivalencia</strong>: punto de la valoración en que se combinan cantidades estequiométricamente equivalentes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.6</a>)</span>. <strong>Reacción de desplazamiento</strong>: reacción en que un elemento metálico desplaza al ion de una sal o un ácido mediante su oxidación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Reacción de metátesis</strong>: reacción en que los cationes y aniones intercambian parejas, también llamada de intercambio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Reacción de neutralización</strong>: reacción entre un ácido y una base que produce agua y una sal <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Reacción de precipitación</strong>: reacción que produce un producto insoluble <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Reacción redox</strong>: reacción de oxidación-reducción en que se transfieren electrones entre reactivos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Reducción</strong>: ganancia de electrones por una sustancia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Sal</strong>: compuesto iónico cuyo catión proviene de una base y cuyo anión proviene de un ácido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.3</a>)</span>. <strong>Serie de actividad</strong>: lista de metales ordenados según la facilidad decreciente de oxidación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>)</span>. <strong>Solubilidad</strong>: cantidad de una sustancia que puede disolverse en una cantidad dada de solvente a cierta temperatura <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.2</a>)</span>. <strong>Soluto</strong>: sustancia que se disuelve en el solvente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Solvatación</strong>: rodeo de los iones disueltos por moléculas de solvente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Solvente</strong>: sustancia presente en mayor cantidad en una disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.1</a>)</span>. <strong>Valoración</strong>: procedimiento que combina una disolución de concentración desconocida con una estándar para determinar la concentración <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.6</a>)</span>. <strong>Análisis dimensional</strong>: método de resolución que multiplica, divide o cancela unidades para garantizar resultados con las unidades correctas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Análisis por combustión</strong>: método que quema un compuesto de carbono e hidrógeno y determina su fórmula empírica por las masas de CO₂ y H₂O retenidas en trampas <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 4.3</a>)</span>. <strong>Balanceo</strong>: determinación de los coeficientes que igualan el número de átomos de cada elemento en ambos lados de la ecuación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.1</a>)</span>. <strong>Cantidades estequiométricamente equivalentes</strong>: moles de reactivos y productos que se corresponden según los coeficientes de la ecuación balanceada <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.6</a>)</span>. <strong>Coeficiente</strong>: número delante de una fórmula que indica las moléculas o moles relativos de esa sustancia en la reacción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.1</a>)</span>. <strong>Composición porcentual</strong>: masa de cada elemento en cien unidades de masa del compuesto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.5</a>)</span>. <strong>Ecuación química</strong>: representación escrita de una reacción con reactivos, productos y coeficientes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.1</a>)</span>. <strong>Fórmula empírica</strong>: fórmula con los subíndices enteros más pequeños que dan la razón de átomos del compuesto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.5</a>)</span>. <strong>Fórmula molecular</strong>: fórmula que da el número real de átomos de cada elemento en la molécula <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 4.4</a>)</span>. <strong>Masa fórmula</strong>: suma de las masas atómicas multiplicadas por los subíndices de la fórmula <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, cap. 2</a>)</span>. <strong>Masa molar</strong>: masa en gramos de un mol de sustancia, numéricamente igual a la masa fórmula en uma <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, cap. 3</a>)</span>. <strong>Mol</strong>: cantidad de sustancia que contiene el número de Avogadro de entidades <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.4</a>)</span>. <strong>Número de Avogadro</strong>: 6,02 × 10²³ mol⁻¹, el número de átomos en exactamente 12 g de carbono-12 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.4</a>)</span>. <strong>Reactivo en exceso</strong>: reactivo que sobra cuando la reacción se detiene por el reactivo limitante <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.7</a>)</span>. <strong>Reactivo limitante</strong>: reactivo que se consume por completo y determina la cantidad de producto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.7</a>)</span>. <strong>Rendimiento porcentual</strong>: cociente entre el rendimiento real y el teórico, multiplicado por cien <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.7</a>)</span>. <strong>Rendimiento real</strong>: cantidad de producto efectivamente obtenida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.7</a>)</span>. <strong>Rendimiento teórico</strong>: cantidad de producto calculada a partir del reactivo limitante <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 3.7</a>)</span>. <strong>Alcano</strong>: hidrocarburo en que cada carbono se enlaza a cuatro átomos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.9</a>)</span>. <strong>Alcohol</strong>: compuesto en que un hidrógeno del alcano se reemplaza por un grupo OH <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.9</a>)</span>. <strong>Alotropía</strong>: existencia de un elemento en más de una forma estructural, como grafito, diamante y fullereno <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 19</a>)</span>. <strong>Anión</strong>: ion con carga negativa <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.7</a>)</span>. <strong>Átomo</strong>: partícula indivisible de la materia, con núcleo y nube de electrones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 2</a>)</span>. <strong>Calor específico</strong>: capacidad de una sustancia para absorber calor por unidad de masa y grado <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 17</a>)</span>. <strong>Calor latente</strong>: calor requerido para fundir un sólido o hervir un líquido sin cambio de temperatura <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 17</a>)</span>. <strong>Cambio físico</strong>: alteración de la apariencia sin cambio de composición <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Cambio químico</strong>: transformación de una sustancia en otra químicamente distinta <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Carga electrónica</strong>: magnitud de la carga del electrón, 1,602 × 10⁻¹⁹ C <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.3</a>)</span>. <strong>Catión</strong>: ion con carga positiva <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.7</a>)</span>. <strong>Celsius</strong>: escala que fija 0 °C y 100 °C en la congelación y ebullición del agua <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 1</a>)</span>. <strong>Cero absoluto</strong>: temperatura mínima posible, −273,15 °C o 0 K <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 1</a>)</span>. <strong>Cifras significativas</strong>: todas las cifras de una medición, incluida la incierta <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Compuesto</strong>: sustancia formada por dos o más elementos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Compuesto iónico</strong>: compuesto eléctricamente neutro de cationes y aniones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.3</a>)</span>. <strong>Densidad</strong>: masa por unidad de volumen <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Elemento</strong>: sustancia que no puede descomponerse en otras más simples <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Entalpía</strong>: calor liberado o absorbido en una reacción a presión constante, simbolizado H <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 17</a>)</span>. <strong>Entropía</strong>: medida del desorden molecular de un sistema, simbolizada S <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 17</a>)</span>. <strong>Equivalente</strong>: peso fijo de una sustancia que reacciona con un peso fijo de otra <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 9</a>)</span>. <strong>Espectrómetro de masas</strong>: instrumento que separa los iones por masa y mide su abundancia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.4</a>)</span>. <strong>Exactitud</strong>: cercanía de una medición al valor verdadero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Fase</strong>: parte homogénea de un sistema separada por límites físicos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 1</a>)</span>. <strong>Filtración</strong>: separación de un sólido y un líquido mediante papel de filtro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Fórmula estructural</strong>: fórmula que muestra qué átomos están unidos a cuáles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.6</a>)</span>. <strong>Gas</strong>: estado sin volumen ni forma fijos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Hidrocarburo</strong>: compuesto que solo contiene carbono e hidrógeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.9</a>)</span>. <strong>Ion</strong>: partícula que ha ganado o perdido electrones <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, 20</a>)</span>. <strong>Isómero</strong>: compuesto con la misma fórmula molecular pero distinto arreglo atómico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.9</a>)</span>. <strong>Isótopos</strong>: átomos del mismo elemento con distinto número de neutrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.3</a>)</span>. <strong>Kelvin</strong>: escala termodinámica cuyo cero es el cero absoluto <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 1</a>)</span>. <strong>Ley de conservación de la masa</strong>: la masa total, incluida la de la energía radiante, se conserva <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 1</a>)</span>. <strong>Ley de la composición constante</strong>: los compuestos tienen composición elemental fija <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Ley de proporciones múltiples</strong>: los pesos de un elemento que reaccionan con un peso fijo de otro están en razón de números enteros pequeños <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 2</a>)</span>. <strong>Ley periódica</strong>: ordenación de los elementos según sus pesos atómicos que agrupa a los químicamente análogos <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 14</a>)</span>. <strong>Líquido</strong>: estado con volumen propio pero sin forma fija <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Materia</strong>: todo lo que tiene masa y ocupa espacio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Metaloide</strong>: elemento con propiedades entre metales y no metales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.5</a>)</span>. <strong>Mezcla</strong>: combinación de sustancias que conservan su identidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Molécula</strong>: agrupación de dos o más átomos unidos en formas específicas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Nanotecnología</strong>: manipulación de la materia a escala atómica o molecular <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 19</a>)</span>. <strong>Natrón</strong>: sal común impura extraída de lagos secos o aguas del Nilo <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 2</a>)</span>. <strong>Número atómico (Z)</strong>: número de protones del núcleo <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 2</a>)</span>. <strong>Número másico (A)</strong>: suma de protones y neutrones del núcleo <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, 20</a>)</span>. <strong>Oxianión</strong>: anión poliatómico que contiene oxígeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.8</a>)</span>. <strong>Peso atómico</strong>: masa relativa de un átomo respecto de la escala acordada en Karlsruhe <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 14</a>)</span>; en su acepción moderna, masa atómica promedio ponderada por la abundancia isotópica <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, 22</a>)</span>. <strong>Precisión</strong>: grado de acuerdo entre mediciones individuales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Propiedad intensiva</strong>: propiedad que no depende de la cantidad de muestra <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Radiactividad</strong>: emisión espontánea de radiación por los átomos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.2</a>)</span>. <strong>Retrosíntesis</strong>: descomposición de una molécula deseada en moléculas simples conocidas para planear su síntesis <span class="citation" data-cites="brock2015">(<a href="../references.html#ref-brock2015" role="doc-biblioref">Brock 2015, cap. 19</a>)</span>. <strong>Sólido</strong>: estado con forma y volumen definidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Solución</strong>: mezcla homogénea <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Sustancia pura</strong>: materia con composición que no varía de muestra a muestra <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Teoría atómica</strong>: doctrina de Dalton según la cual la materia es particulada y los compuestos se forman combinando átomos en proporciones fijas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.1</a>)</span>; y cada compuesto se forma con razones de números enteros pequeños <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, cap. 2</a>)</span>. <strong>Unidad de masa atómica (uma)</strong>: exactamente un doceavo de la masa del carbono-12 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 2.4</a>)</span>. <strong>Unidades SI</strong>: unidades métricas preferidas acordadas internacionalmente en 1960 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 1</a>)</span>. <strong>Actínidos</strong>: serie de catorce elementos que siguen al actinio, cuyos núcleos son todos radiactivos y que ocupan la subcapa 5f <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Amplitud</strong>: altura de una onda, una de las tres propiedades que la caracterizan junto con la longitud de onda y la frecuencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.1</a>)</span>. <strong>Bloques de la tabla periódica</strong>: divisiones de la tabla según la subcapa que se está llenando, s, p, d o f, con 2, 6, 10 y 14 columnas respectivamente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.9</a>)</span>. <strong>Capa electrónica</strong>: conjunto de orbitales con el mismo número cuántico principal n, que contiene n² orbitales <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Configuración electrónica</strong>: distribución de los electrones de un átomo entre los orbitales disponibles, escrita anotando la subcapa y su ocupación como superíndice <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Constante de Planck</strong>: constante de proporcionalidad h entre la energía de un cuanto y la frecuencia de la radiación, 6,626 × 10⁻³⁴ J·s <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.2</a>)</span>. <strong>Constante de Rydberg</strong>: constante R_H de la ecuación de Rydberg, 1,096776 × 10⁷ m⁻¹, que fija la escala de las líneas del espectro del hidrógeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Cuanto</strong>: paquete discreto de energía que los átomos solo pueden emitir o absorber, base de la cuantización de Planck <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.2</a>)</span>. <strong>Densidad de probabilidad</strong>: cuadrado de la función de onda, ψ², la probabilidad de hallar al electrón por unidad de volumen en cada punto del espacio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Difracción</strong>: desvío de las ondas de materia al atravesar un cristal, fenómeno que verificó experimentalmente el carácter ondulatorio del electrón <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 3–8</a>)</span>. <strong>Ecuación de Rydberg</strong>: fórmula que predice la longitud de onda de cada línea del espectro del hidrógeno a partir de dos números enteros n₁ y n₂ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Efecto fotoeléctrico</strong>: emisión de electrones por una superficie metálica iluminada, explicada por Einstein en 1905 con fotones de energía hν <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.2</a>)</span>. <strong>Electrones de core</strong>: electrones internos del átomo, los del gas noble precedente en la notación condensada, que no participan en el enlace <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Electrones de valencia</strong>: electrones de la capa exterior del átomo, responsables de su comportamiento químico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Electronvoltio</strong>: energía que adquiere un electrón acelerado por una diferencia de potencial de un voltio, 1,602 × 10⁻¹⁹ J <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 3–6</a>)</span>. <strong>Elementos representativos</strong>: elementos de los bloques s y p, cuyos electrones de valencia se leen directamente del grupo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.9</a>)</span>. <strong>Energía de ionización</strong>: energía necesaria para llevar un electrón desde el estado fundamental hasta el estado libre, que en el hidrógeno vale 13,60 electronvoltios <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–1</a>)</span>. <strong>Espectro continuo</strong>: espectro con todas las longitudes de onda, producido por la luz blanca descompuesta en un espectroscopio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Espectro de líneas</strong>: conjunto de líneas aisladas de la luz emitida por un gas caliente, característico de cada elemento <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Espectro electromagnético</strong>: conjunto completo de longitudes de onda posibles de la radiación, ordenado de las ondas largas a las cortas: radio, microondas, infrarrojo, visible, ultravioleta, rayos X y rayos gamma <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.1</a>)</span>. <strong>Espín electrónico</strong>: momento angular intrínseco del electrón, parecido al de un trompo, con dos orientaciones posibles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.7</a>)</span>. <strong>Estado excitado</strong>: estado del electrón con energía mayor que la del estado fundamental <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–1</a>)</span>. <strong>Estado estacionario</strong>: estado de energía fija en el que el electrón no irradia energía mientras permanece en él, postulado de Bohr <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Estado fundamental</strong>: estado del electrón con la menor energía posible <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–1</a>)</span>. <strong>Fotón</strong>: partícula de luz postulada por Einstein, cada una con energía hν <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.2</a>)</span>. <strong>Frecuencia</strong>: número de ciclos de una onda que pasan por un punto fijo cada segundo, medido en ciclos por segundo o hercios <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.1</a>)</span>. <strong>Función de onda</strong>: solución de la ecuación de Schrödinger para cada estado del electrón, simbolizada ψ, cuyo cuadrado posee significado físico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Función trabajo</strong>: energía umbral de un metal para arrancar un electrón en el efecto fotoeléctrico, la Eᵢ de la ecuación de Einstein <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.2</a>)</span>. <strong>Lantánidos</strong>: serie de catorce elementos que siguen al lantano, que ocupan la subcapa 4f y se colocan aparte en la tabla por sus propiedades muy similares <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Ley periódica moderna</strong>: las propiedades de los elementos son funciones periódicas de sus configuraciones electrónicas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Longitud de onda</strong>: distancia entre picos sucesivos de una onda, simbolizada λ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.1</a>)</span>. <strong>Mecánica cuántica</strong>: mecánica fundada por Schrödinger y Heisenberg en 1926 que describe al electrón con funciones de onda y niveles discretos de energía <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Metales de transición</strong>: elementos que ocupan sucesivamente los orbitales d de cada periodo, del escandio al cinc en el cuarto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Nodo</strong>: superficie donde la densidad de probabilidad del electrón se anula, como el nodo esférico del orbital 2s <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.6</a>)</span>. <strong>Notación condensada</strong>: escritura abreviada de una configuración electrónica que usa el símbolo del gas noble precedente entre corchetes como núcleo inerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Nube electrónica</strong>: imagen estadística del electrón como distribución difusa de probabilidad que rodea al núcleo, cuya concentración máxima en el hidrógeno se halla a 0,53 Å <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–3</a>)</span>. <strong>Número cuántico azimutal</strong>: número l que fija la forma del orbital y toma valores de 0 hasta n − 1, representados por las letras s, p, d y f <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Número cuántico de espín</strong>: número mₛ que solo puede valer +½ o −½ y da las dos orientaciones posibles del espín <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.7</a>)</span>. <strong>Número cuántico magnético</strong>: número mₗ que fija la orientación de un orbital y toma valores desde −l hasta +l <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Número cuántico principal</strong>: número n que fija el tamaño y la energía del orbital y toma valores enteros desde 1 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Onda de materia</strong>: onda asociada a toda partícula en movimiento, cuya longitud de onda es la constante de Planck dividida entre el momentum, λ = h/mv <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.4</a>)</span>. <strong>Orbital</strong>: función de onda permitida, región del espacio donde el electrón pasa la mayor parte del tiempo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Orbitales degenerados</strong>: orbitales de la misma energía, como los 3s, 3p y 3d del hidrógeno, cuya degeneración rompe la repulsión en átomos con varios electrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.7</a>)</span>. <strong>Penetración</strong>: capacidad de un orbital de adentrarse en la nube cercana al núcleo, donde el apantallamiento es menor, que hace más estables los orbitales s <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.7</a>)</span>. <strong>Principio de exclusión de Pauli</strong>: en un átomo no pueden existir dos electrones con los cuatro números cuánticos idénticos, de modo que cada orbital admite a lo sumo dos electrones de espines opuestos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.7</a>)</span>. <strong>Principio de incertidumbre</strong>: es imposible conocer simultáneamente con precisión arbitraria la posición y el momentum de una partícula, con Δx·Δ(mv) ≥ h/4π <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.4</a>)</span>. <strong>Radiación electromagnética</strong>: forma de energía que se propaga como ondas de campos eléctrico y magnético perpendiculares, e incluye la luz visible, los rayos ultravioleta y los rayos X <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 3–5</a>)</span>. <strong>Radio de Bohr</strong>: radio de la primera órbita del hidrógeno, 0,53 Å, conservado por la mecánica cuántica como la distancia más probable del electrón al núcleo <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988</a>, secs. 5-1, 5-3)</span>. <strong>Regla de frecuencia de Bohr</strong>: la energía del fotón emitido o absorbido en una transición es exactamente la diferencia entre las energías de los dos estados estacionarios <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–1</a>)</span>. <strong>Regla de Hund</strong>: la configuración de menor energía es la que maximiza el número de electrones desapareados de espín paralelo, ocupando cada orbital de una subcapa antes de aparear ninguno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.8</a>)</span>. <strong>Serie de Balmer</strong>: conjunto de líneas visibles del espectro del hidrógeno, con n₁ = 2 en la ecuación de Rydberg <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Serie de Lyman</strong>: serie del espectro del hidrógeno en el ultravioleta, con n₁ = 1 en la ecuación de Rydberg, descubierta por Lyman en 1915 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Subcapa</strong>: nivel definido por la combinación de n y l que contiene 2l + 1 orbitales, uno por cada orientación de mₗ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.5</a>)</span>. <strong>Transición electrónica</strong>: salto del electrón entre estados estacionarios, acompañado de emisión o absorción de un fotón <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.3</a>)</span>. <strong>Velocidad de la luz</strong>: constante c que liga longitud de onda y frecuencia de toda onda electromagnética, 3,00 × 10⁸ metros por segundo en el vacío <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 6.1</a>)</span>. <strong>Afinidad electrónica</strong>: variación de entalpía al añadir un electrón a un átomo gaseoso; negativa cuando libera energía, como en el cloro, con −349 kJ/mol <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.5</a>)</span>. <strong>Alótropo</strong>: forma alternativa del mismo elemento en el mismo estado físico, como el O₂ y el O₃ o como los anillos S₈ del azufre <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. <strong>Carga nuclear efectiva</strong>: carga neta que percibe un electrón, Z − S, menor que la nuclear por el apantallamiento de los electrones internos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. <strong>Carácter metálico</strong>: grado en que un elemento se comporta como metal; crece al bajar en el grupo y decrece hacia la derecha del periodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. <strong>Congéneres</strong>: elementos de un mismo grupo, con configuraciones exteriores parecidas y propiedades estrechamente relacionadas <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Constante de apantallamiento</strong>: fracción de la carga nuclear, en unidades electrónicas, que los electrones interiores ocultan al electrón de valencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. <strong>Dopante</strong>: impureza deliberada que controla la conductividad de un semiconductor como el silicio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. <strong>Energías de ionización sucesivas</strong>: I₁, I₂, I₃…, las energías para arrancar el primer, el segundo y el tercer electrón de un átomo gaseoso, siempre crecientes <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.4</a>)</span>. <strong>Gases nobles</strong>: grupo 8A; monoatómicos, con subcapas s y p llenas y energías de ionización máximas; el xenón y el kriptón reaccionan con el flúor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. <strong>Grupo</strong>: columna vertical de la tabla periódica; sus miembros, los congéneres, comparten la configuración exterior <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Halógenos</strong>: grupo 7A; moléculas diatómicas X₂, con la afinidad electrónica más negativa de la tabla <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. <strong>Hidruro</strong>: compuesto de un metal activo y el hidrógeno, en el que este actúa como ion H⁻ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Ion hidruro</strong>: ion mononegativo H⁻, con la configuración del helio; presente en los hidruros de los metales alcalinos y alcalinotérreos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Ley de las octavas</strong>: regularidad descrita por Newlands en 1863, según la cual cada octavo elemento de la lista por peso atómico repite el comportamiento químico <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>. <strong>Metales alcalinos</strong>: grupo 1A; blandos, de baja densidad, con la energía de ionización mínima de su periodo y estado de oxidación +1 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Metales alcalinotérreos</strong>: grupo 2A; más duros y densos que los alcalinos, con estado de oxidación +2 y reactividad moderada <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Octeto</strong>: configuración de ocho electrones exteriores ns²np⁶ propia de los gases nobles, salvo el helio; meta de la valencia iónica <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Óxido ácido</strong>: óxido de no metal que con el agua forma un ácido y con las bases una sal y agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. <strong>Óxido básico</strong>: óxido de metal que con el agua forma un hidróxido y con los ácidos una sal y agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. <strong>Ozono</strong>: alótropo O₃ del oxígeno; protector en la estratosfera y oxidante nocivo a ras de suelo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.8</a>)</span>. <strong>Período</strong>: fila horizontal de la tabla periódica; contiene 2, 8, 8, 18, 18 o 32 elementos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Peróxido</strong>: compuesto con el ion O₂²⁻, que el sodio y los alcalinos más pesados forman con el oxígeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Radio atómico de enlace</strong>: mitad de la distancia entre los núcleos de dos átomos enlazados; 1,33 Å para el yodo y 0,77 Å para el carbono <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. <strong>Radio de van der Waals</strong>: mitad de la distancia mínima entre los núcleos de átomos no enlazados que colisionan <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. <strong>Radio iónico</strong>: tamaño de un ion, estimado al repartir la distancia catión-anión en los cristales iónicos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. <strong>Reglas de Slater</strong>: método para estimar la constante de apantallamiento: 0,35 por cada electrón del mismo nivel, 0,85 por los de la capa interior y 1,00 por los más profundos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.2</a>)</span>. <strong>Semiconductor</strong>: sólido de conductividad intermedia, creciente con la temperatura, como el silicio dopado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.6</a>)</span>. <strong>Serie isoelectrónica</strong>: grupo de iones con igual número de electrones y radios decrecientes al crecer el número atómico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.3</a>)</span>. <strong>Símbolos de punto de Lewis</strong>: representación del electrón de valencia como puntos alrededor del símbolo del elemento <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–4</a>)</span>. <strong>Superóxido</strong>: compuesto con el ion O₂⁻, que potasio, rubidio y cesio forman con el oxígeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 7.7</a>)</span>. <strong>Tríadas</strong>: tríos de elementos de propiedades semejantes que Döbereiner señaló en 1817 <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 5–6</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-atkins2015" class="csl-entry" role="listitem">
Atkins, Peter. 2015. <em>Chemistry: A Very Short Introduction</em>. 1st ed. Oxford University Press. <a href="https://doi.org/10.1093/actrade/9780199683970.001.0001">https://doi.org/10.1093/actrade/9780199683970.001.0001</a>.
</div>
<div id="ref-brock2015" class="csl-entry" role="listitem">
Brock, William H. 2015. <em>The History of Chemistry: A Very Short Introduction</em>. 1st ed. Oxford University Press.
</div>
<div id="ref-brown2012" class="csl-entry" role="listitem">
Brown, Theodore L., H. Eugene LeMay, Bruce E. Bursten, Catherine J. Murphy, y Patrick M. Woodward. 2012. <em>Chemistry: The Central Science</em>. 12th ed. Pearson Prentice Hall.
</div>
<div id="ref-oriakhi2021" class="csl-entry" role="listitem">
Oriakhi, Christopher O. 2021. <em>Chemistry in Quantitative Language: Fundamentals of General Chemistry Calculations</em>. 2nd ed. Oxford University Press.
</div>
<div id="ref-pauling1988" class="csl-entry" role="listitem">
Pauling, Linus. 1988. <em>General Chemistry</em>. 3rd (reprinted). Dover Publications.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../02_quimica/06-estructura-electronica-del-atomo.html" class="pagination-link" aria-label="Capítulo 6 · Estructura electrónica del átomo">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Capítulo 6 · Estructura electrónica del átomo</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../02_quimica/08-enlace-quimico-i-conceptos-fundamentales.html" class="pagination-link" aria-label="Capítulo 8 · Enlace químico I: conceptos fundamentales">
        <span class="nav-page-text"><span class="chapter-title">Capítulo 8 · Enlace químico I: conceptos fundamentales</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>