<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Equilibrios ácido-base y de solubilidad: aplicaciones – Nous</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../02_quimica/18-termodinamica-quimica.html" rel="next">
<link href="../02_quimica/16-acidos-y-bases.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-53aca5cea238aca1de29c5a91d105b8d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-title">Equilibrios ácido-base y de solubilidad: aplicaciones</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Nous</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nous</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Conjuntos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_conjuntos/00_proposicion_negacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Proposición y su negación</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Química</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/01-historia-de-la-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 1 · La química en la historia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/02-materia-y-medicion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 2 · La materia y su medición</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/03-atomos-moleculas-e-iones.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 3 · Átomos, moléculas e iones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/04-estequiometria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estequiometría: moles, fórmulas y ecuaciones químicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/05-reacciones-en-disolucion-acuosa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reacciones en disolución acuosa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/06-estructura-electronica-del-atomo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estructura electrónica del átomo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/07-tabla-periodica-y-propiedades-periodicas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tabla periódica y propiedades periódicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/08-enlace-quimico-i-conceptos-fundamentales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Enlace químico I: conceptos fundamentales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/09-enlace-quimico-ii-geometria-molecular-y-teorias-de-enlace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Enlace químico II: geometría molecular y teorías de enlace</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/10-gases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/11-termoquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Termoquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/12-liquidos-fuerzas-intermoleculares-y-solidos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Líquidos, fuerzas intermoleculares y sólidos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/13-disoluciones-y-propiedades-coligativas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Disoluciones y propiedades coligativas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/14-cinetica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cinética química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/15-equilibrio-quimico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Equilibrio químico</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/16-acidos-y-bases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ácidos y bases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/17-equilibrios-acido-base-y-solubilidad.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Equilibrios ácido-base y de solubilidad: aplicaciones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/18-termodinamica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Termodinámica química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/19-electroquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Electroquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/20-quimica-nuclear.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química nuclear</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/21-quimica-de-los-no-metales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química de los no metales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/22-quimica-de-los-metales-de-transicion-y-quimica-de-coordinacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química de los metales de transición y química de coordinación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/23-quimica-organica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química orgánica: la química de los compuestos del carbono</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/24-bioquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bioquímica: la química de la vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/25-quimica-del-ambiente.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química del ambiente: atmósfera, agua y química verde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/26-quimica-moderna-tecnicas-y-fronteras.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">La química moderna: técnicas, logros y fronteras</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Biología</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_biologia/01_base_fisica_herencia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">La base física de la herencia</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#el-efecto-del-ion-común" id="toc-el-efecto-del-ion-común" class="nav-link" data-scroll-target="#el-efecto-del-ion-común">El efecto del ion común</a></li>
  <li><a href="#disoluciones-amortiguadoras-tampones" id="toc-disoluciones-amortiguadoras-tampones" class="nav-link" data-scroll-target="#disoluciones-amortiguadoras-tampones">Disoluciones amortiguadoras (tampones)</a></li>
  <li><a href="#capacidad-amortiguadora-y-rango-de-ph" id="toc-capacidad-amortiguadora-y-rango-de-ph" class="nav-link" data-scroll-target="#capacidad-amortiguadora-y-rango-de-ph">Capacidad amortiguadora y rango de pH</a></li>
  <li><a href="#valoraciones-ácido-base" id="toc-valoraciones-ácido-base" class="nav-link" data-scroll-target="#valoraciones-ácido-base">Valoraciones ácido-base</a></li>
  <li><a href="#indicadores-ácido-base" id="toc-indicadores-ácido-base" class="nav-link" data-scroll-target="#indicadores-ácido-base">Indicadores ácido-base</a></li>
  <li><a href="#ácidos-polipróticos-etapas-sucesivas-y-su-valoración" id="toc-ácidos-polipróticos-etapas-sucesivas-y-su-valoración" class="nav-link" data-scroll-target="#ácidos-polipróticos-etapas-sucesivas-y-su-valoración">Ácidos polipróticos: etapas sucesivas y su valoración</a></li>
  <li><a href="#el-producto-de-solubilidad-kps" id="toc-el-producto-de-solubilidad-kps" class="nav-link" data-scroll-target="#el-producto-de-solubilidad-kps">El producto de solubilidad (Kps)</a></li>
  <li><a href="#el-producto-iónico-y-la-predicción-de-precipitación" id="toc-el-producto-iónico-y-la-predicción-de-precipitación" class="nav-link" data-scroll-target="#el-producto-iónico-y-la-predicción-de-precipitación">El producto iónico y la predicción de precipitación</a></li>
  <li><a href="#factores-que-alteran-la-solubilidad-ion-común-ph-e-iones-complejos" id="toc-factores-que-alteran-la-solubilidad-ion-común-ph-e-iones-complejos" class="nav-link" data-scroll-target="#factores-que-alteran-la-solubilidad-ion-común-ph-e-iones-complejos">Factores que alteran la solubilidad: ion común, pH e iones complejos</a></li>
  <li><a href="#precipitación-fraccionada-y-análisis-cualitativo" id="toc-precipitación-fraccionada-y-análisis-cualitativo" class="nav-link" data-scroll-target="#precipitación-fraccionada-y-análisis-cualitativo">Precipitación fraccionada y análisis cualitativo</a></li>
  <li><a href="#ejemplo-resuelto" id="toc-ejemplo-resuelto" class="nav-link" data-scroll-target="#ejemplo-resuelto">Ejemplo resuelto</a></li>
  <li><a href="#preguntas-y-ejercicios" id="toc-preguntas-y-ejercicios" class="nav-link" data-scroll-target="#preguntas-y-ejercicios">Preguntas y ejercicios</a></li>
  <li><a href="#solucionario" id="toc-solucionario" class="nav-link" data-scroll-target="#solucionario">Solucionario</a></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen">Resumen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-title">Equilibrios ácido-base y de solubilidad: aplicaciones</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>Las herramientas cuantitativas del capítulo anterior, las constantes Ka y Kb y las escalas de pH y pOH, encuentran aquí su aplicación más rica en tres territorios de la química acuosa <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 17</a>)</span>. Las disoluciones amortiguadoras mantienen el pH casi inmóvil frente a la adición de ácidos o bases, las valoraciones convierten la neutralización en un método de medida y los equilibrios de solubilidad explican desde la caries dental hasta la separación de iones en el laboratorio <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, cap. 16</a>)</span>. Un denominador común recorre estos problemas: el principio de Le Châtelier aplicado a equilibrios gobernados por constantes <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14-6, 14-7</a>)</span>.</p>
<p>La utilidad práctica de estos equilibrios es difícil de exagerar: la sangre humana depende de sistemas amortiguadores para permanecer cerca de pH 7.4, el diagnóstico digestivo emplea el sulfato de bario insoluble, y la identificación de desconocidos iónicos reposa sobre la precipitación selectiva <span class="citation" data-cites="chang2022 brown2012 pauling1988">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2, 16.5, 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2, 17.7</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>. El orden de exposición sigue la lógica del problema: primero el efecto del ion común, que gobierna tampones y solubilidad, después la valoración y sus indicadores, y finalmente el producto de solubilidad con sus factores y aplicaciones analíticas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 17</a>)</span>.</p>
</section>
<section id="el-efecto-del-ion-común" class="level2">
<h2 class="anchored" data-anchor-id="el-efecto-del-ion-común">El efecto del ion común</h2>
<p>Una disolución que contiene dos solutos con un ion en común se comporta de manera distinta a la suma de sus partes: la presencia del ion compartido suprime la ionización del ácido o de la base débil, y el resultado es un desplazamiento predecible del equilibrio <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.1</a>)</span>.</p>
<p>Si se disuelven simultáneamente ácido acético y acetato de sodio, ambos aportan iones acetato, y el exceso de estos iones desplaza el equilibrio de ionización del ácido hacia la izquierda, disminuyendo la concentración de iones hidrógeno <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. El <span id="sec-efecto-ion-comun"><strong>efecto del ion común</strong></span> es, por tanto, un caso especial del principio de Le Châtelier, y desempeña un papel central en el pH de las disoluciones y en la solubilidad de las sales poco solubles <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.1</a>)</span>.</p>
<p>La magnitud del desplazamiento se obtiene con la constante del ácido débil, cuyo valor no cambia por la presencia de la sal <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. En una disolución 0.20 M de ácido acético, con Ka = 1.8 × 10⁻⁵, la ionización produce [H⁺] = 1.9 × 10⁻³ M y un pH de 2.72 <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>.</p>
<p>Al añadir acetato de sodio hasta 0.30 M, el ion común reduce la concentración de hidrógeno a 1.2 × 10⁻⁵ M y eleva el pH a 4.92, casi dos unidades más alto <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. La misma lógica vale para una base débil: el amoniaco 0.20 M con cloruro de amonio 0.30 M resulta menos básico que el amoniaco solo, porque el ion amonio común suprime la aceptación de protones <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>.</p>
<p>Cuando las concentraciones del ácido débil y de su sal son razonablemente altas, superiores a 0.01 M, puede despreciarse tanto la ionización del ácido como la hidrólisis de la sal <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. Esta aproximación permite usar las concentraciones iniciales directamente en la expresión de Ka, y conduce a una forma logarítmica especialmente cómoda <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. La manipulación algebraica de la constante, tomando logaritmos negativos en ambos miembros, produce la ecuación que domina el cálculo de los tampones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.1</a>)</span>.</p>
<p><span id="eq-henderson-hasselbalch"><span class="math display">\[pH = pK_a + \log\frac{[\mathrm{A^-}]}{[\mathrm{HA}]}, \tag{18.1}\]</span></span></p>
<p>La expresión (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>) relaciona el pH con el pKa del ácido débil, definido como el logaritmo negativo de su constante, y con el cociente entre las concentraciones de la base conjugada A⁻ y del ácido HA <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. La variable [A⁻] representa la concentración molar del ion acetato o de cualquier base conjugada, [HA] la del ácido sin ionizar, y el logaritmo en base diez del cociente añade o resta fracciones de unidad al pKa <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Cuando ambas concentraciones se igualan, el logaritmo se anula y el pH coincide exactamente con el pKa, hecho que permite calibrar la escala con un solo parámetro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>La ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>), conocida como <span id="sec-henderson-hasselbalch"><strong>ecuación de Henderson-Hasselbalch</strong></span>, es válida con independencia de la procedencia de la base conjugada, ya provenga del ácido solo o la suministren el ácido y su sal <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. Los biólogos y bioquímicos que trabajan con tampones la emplean de forma rutinaria porque evita plantear tablas de equilibrio, y porque su forma logarítmica hace evidente la relación entre el pH y la proporción de las especies <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. En los problemas de ion común suelen darse las concentraciones iniciales, y la validez de la aproximación se verifica comprobando que el grado de ionización permanece despreciable <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>.</p>
</section>
<section id="disoluciones-amortiguadoras-tampones" class="level2">
<h2 class="anchored" data-anchor-id="disoluciones-amortiguadoras-tampones">Disoluciones amortiguadoras (tampones)</h2>
<p>Las <span id="sec-soluciones-amortiguadoras"><strong>disoluciones amortiguadoras</strong></span>, también llamadas tampones o soluciones buffer, son mezclas de un ácido débil y su base conjugada, o de una base débil y su ácido conjugado, que resisten el cambio de pH al añadir cantidades moderadas de ácidos o bases fuertes <span class="citation" data-cites="brown2012 chang2022 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
<p>La resistencia no es mágica: el componente ácido consume los iones hidróxido añadidos y el componente básico consume los iones hidrógeno, de modo que la proporción entre ambas especies cambia apenas <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>)</span>. Una gota de ácido concentrado en un litro de agua pura multiplica la concentración de iones hidrógeno por 5000, mientras que en un tampón fosfato ese mismo aumento no llega al uno por ciento <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
<p>La sangre ilustra la importancia biológica de los tampones, pues su pH normal, cercano a 7.4, solo cambia lentamente cuando se añade ácido o base <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Entre las sustancias amortiguadoras del organismo figuran las proteínas del suero, con grupos ácidos y básicos capaces de combinarse con lo añadido, y el par carbónico-bicarbonato cuya concentración regula la respiración <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. En contraste, el jugo gástrico mantiene un pH cercano a 1.5, y el lavado de los riñones y los pulmones ajusta el sistema según las necesidades del cuerpo <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>)</span>.</p>
<p>El cálculo del pH de un tampón es directo con la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>): un tampón 0.12 M en ácido benzoico y 0.20 M en benzoato de sodio, con pKa del ácido igual a 4.20, produce un pH de 4.42 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El resultado puede obtenerse también con la tabla de equilibrio convencional, y ambas rutas coinciden porque la única diferencia es la forma de presentar los mismos términos algebraicos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. La preparación inversa, calcular la cantidad de sal necesaria para lograr un pH deseado, se resuelve despejando la concentración del conjugado en la misma expresión <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Pauling ilustra la neutralidad del punto medio con el par acético-acetato: cuando las concentraciones del ácido y de su sal son iguales, el pH coincide con el pKa del ácido, 4.7 para el acético <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>. Variar la proporción desplaza el pH: una mezcla 1:5 de ácido y sal da pH 5.4, y una mezcla 5:1 da pH 4.0, de modo que eligiendo la proporción puede fijarse cualquier pH deseado en ese vecindario <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>. El tampón fosfato, preparado con KH₂PO₄ y Na₂HPO₄·2H₂O, sirve para la región neutra con pH entre 5.3 y 8.0, y otros pares cubren rangos desde 1 hasta 13 <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
</section>
<section id="capacidad-amortiguadora-y-rango-de-ph" class="level2">
<h2 class="anchored" data-anchor-id="capacidad-amortiguadora-y-rango-de-ph">Capacidad amortiguadora y rango de pH</h2>
<p>Dos características distinguen a los tampones útiles: la <span id="sec-capacidad-amortiguadora"><strong>capacidad amortiguadora</strong></span>, cantidad de ácido o base que pueden neutralizar antes de que el pH cambie de forma apreciable, y el <span id="sec-rango-ph"><strong>rango de pH</strong></span> en el que actúan eficazmente; juntas definen la ventana de uso de cada tampón <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>)</span>.</p>
<p>La capacidad depende de la cantidad de ácido y de base con que se preparó el tampón: dos disoluciones 1 M y 0.1 M en acetato tienen el mismo pH, pero la primera neutraliza diez veces más ácido o base antes de moverse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. La dilución por diez de un tampón reduce en el mismo factor la cantidad de ácido o base que puede absorber sin salirse del margen deseado <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
<p>El rango de acción eficaz se centra en el pKa del ácido: el tampón resiste mejor cuando las concentraciones del ácido y de su base conjugada son semejantes, y su actuación se deteriora cuando un componente supera diez veces al otro, lo que delimita el margen práctico de trabajo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Como el logaritmo de diez vale uno, los tampones tienen un margen útil de pH = pKa ± 1, de modo que la elección de un par amortiguador comienza por buscar un ácido cuyo pKa esté cerca del pH deseado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Para un pH de 7.0 conviene, por ejemplo, el ácido hipocloroso, con pKa 7.5, y no el nitroso, cuyo pKa es de 3.35 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>La respuesta cuantitativa de un tampón a la adición de un ácido o una base fuerte se resuelve en dos pasos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Primero se realiza un cálculo estequiométrico: el ácido fuerte reacciona por completo con la base conjugada del tampón, y la base fuerte con el ácido débil, siempre que no se rebase la capacidad <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Después se introduce la nueva composición en la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>), obteniendo el pH con las cantidades ya ajustadas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Esta estrategia revela la magnitud de la protección: un tampón de 0.300 mol de ácido acético y 0.300 mol de acetato en un litro, con pH 4.74, pasa a 4.80 al añadir 0.020 mol de hidróxido de sodio, mientras que la misma cantidad de base eleva el pH del agua pura desde 7 hasta 12.30 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. La diferencia se entiende recordando que el agua no tiene reserva alguna de ácido débil que consuma el hidróxido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El mismo razonamiento vale para la adición de un ácido fuerte, que el tampón convierte en una pequeña variación de la proporción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
</section>
<section id="valoraciones-ácido-base" class="level2">
<h2 class="anchored" data-anchor-id="valoraciones-ácido-base">Valoraciones ácido-base</h2>
<p>Una <span id="sec-valoraciones-acido-base"><strong>valoración ácido-base</strong></span> determina la concentración de un ácido o de una base haciendo reaccionar la disolución problema con una disolución de concentración conocida, añadida con una bureta hasta completar la neutralización <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.3</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La relación estequiométrica entre el volumen gastado y la concentración del titulante permite calcular los moles de analito, y de ahí su molaridad <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.3</a>)</span>. La reacción entre un ácido fuerte y una base fuerte es esencialmente completa: los iones hidrógeno y los iones hidróxido se neutralizan entre sí formando agua <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.3</a>)</span>.</p>
<p>El progreso de la valoración se representa con la <span id="sec-curva-valoracion"><strong>curva de valoración</strong></span>, gráfica del pH frente al volumen de disolución añadida, cuya forma depende de las fuerzas relativas de las especies <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. En la valoración de un ácido fuerte con una base fuerte el pH inicial es bajo, crece lentamente, y salta bruscamente en las inmediaciones del <span id="sec-punto-equivalencia"><strong>punto de equivalencia</strong></span>, el momento en que el número de moles de base añadida es exactamente el estequiométricamente equivalente al ácido presente <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.3</a>)</span>. Para un par fuerte-fuerte, el pH en el punto de equivalencia es 7, porque la sal formada no se hidroliza <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Cuando el ácido es débil, la curva cambia de aspecto: el pH inicial es más alto que el de un ácido fuerte de la misma concentración, el salto cerca del punto de equivalencia es menor, y el pH en ese punto supera 7, pues el anión de la sal formada es una base débil que se hidroliza <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La valoración del ácido acético 0.100 M con hidróxido de sodio 0.100 M alcanza el punto de equivalencia en un pH de 8.72, por ejemplo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Cuanto más débil es el ácido, más pronunciadas se vuelven estas diferencias, hasta el punto de que resulta prácticamente imposible localizar el punto de equivalencia cuando el pKa es 10 o mayor, porque el cambio de pH es demasiado pequeño y gradual <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>La simetría se completa con la valoración de una base débil con un ácido fuerte, cuyo punto de equivalencia cae por debajo de 7 porque el ion amonio u otro ácido conjugado libera protones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La titulación del amoniaco 0.100 M con ácido clorhídrico 0.100 M termina en pH 5.28, valor que exige un indicador que cambie de color en esa zona ácida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. En todos los casos, el pH de cada etapa se calcula combinando primero la estequiometría de la neutralización y después el equilibrio de las especies que quedan en disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Los ácidos polipróticos y las bases polibásicas, cuando sus etapas de neutralización están suficientemente separadas, producen curvas de valoración con varios puntos de equivalencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. El ácido carbónico, por ejemplo, muestra dos saltos de pH, correspondientes a la neutralización sucesiva de sus dos protones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La curva de valoración del ácido fosfórico con una base fuerte, que Pauling emplea para explicar los tampones, exhibe igualmente dos puntos de inflexión netos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
</section>
<section id="indicadores-ácido-base" class="level2">
<h2 class="anchored" data-anchor-id="indicadores-ácido-base">Indicadores ácido-base</h2>
<p>Un <strong>indicador ácido-base</strong> es un ácido orgánico débil cuya forma sin ionizar, HIn, tiene un color distinto al de su base conjugada, In⁻, de modo que el color de la disolución revela el pH <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. El equilibrio HIn ⇌ H⁺ + In⁻ se desplaza con el pH: en medio ácido predomina la forma sin ionizar y en medio básico la ionizada <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>)</span>.</p>
<p>El <span id="sec-punto-final"><strong>punto final</strong></span> es el instante en que el indicador cambia de color, y para que la valoración sea exacta debe coincidir con el punto de equivalencia, lo que exige elegir un indicador cuyo cambio de color ocurra en el salto brusco de la curva <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>El criterio de elección cuantitativo es sencillo: el pKa del indicador debe aproximarse al pH del punto de equivalencia de la valoración <span class="citation" data-cites="pauling1988 chang2022 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. Para un ácido fuerte frente a una base fuerte, cuyo punto de equivalencia está en pH 7, casi cualquier indicador con pKa entre 4 y 10 produce un error menor del 0.2%, porque la curva es tan vertical que diferentes indicadores cambian a volúmenes casi idénticos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>)</span>. La fenolftaleína, con pKa de 9, es la elección clásica para un ácido débil como el acético, cuyo punto de equivalencia se sitúa en pH 8.87 por la hidrólisis del acetato <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>)</span>.</p>
<div class="table-responsive">
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Indicador</th>
<th style="text-align: left;">Rango o pKa</th>
<th style="text-align: left;">Valoración típica</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Naranja de metilo</td>
<td style="text-align: left;">pKa 3.8</td>
<td style="text-align: left;">Base débil con ácido fuerte <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Rojo de metilo</td>
<td style="text-align: left;">4.2 a 6.0</td>
<td style="text-align: left;">Base débil con ácido fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tornasol, azul de bromotimol</td>
<td style="text-align: left;">pKa ~ 7</td>
<td style="text-align: left;">Ácido fuerte con base fuerte <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>)</span></td>
</tr>
<tr class="even">
<td style="text-align: left;">Fenolftaleína</td>
<td style="text-align: left;">8.3 a 10.0</td>
<td style="text-align: left;">Ácido débil con base fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Timolftaleína</td>
<td style="text-align: left;">pKa 10</td>
<td style="text-align: left;">Ácido fuerte con base fuerte <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>)</span></td>
</tr>
</tbody>
</table>
</div>
<p>La elección incorrecta produce errores sistemáticos: valorar ácido acético 0.100 M con hidróxido de sodio 0.100 M empleando rojo de metilo daría un cambio de color en pH de 4.2 a 6.0, mucho antes del punto de equivalencia de 8.72 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La fenolftaleína, en cambio, cambia entre 8.3 y 10.0, justo en la zona de salto abrupto del pH <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. Para la valoración inversa, amoniaco con ácido clorhídrico, el punto de equivalencia de 5.28 convierte al rojo de metilo en la elección natural, y a la fenolftaleína en una elección desafortunada <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
</section>
<section id="ácidos-polipróticos-etapas-sucesivas-y-su-valoración" class="level2">
<h2 class="anchored" data-anchor-id="ácidos-polipróticos-etapas-sucesivas-y-su-valoración">Ácidos polipróticos: etapas sucesivas y su valoración</h2>
<p>El capítulo anterior introdujo los <strong>ácidos polipróticos</strong> y la regla de que el pH de sus disoluciones puede estimarse con la primera constante, pero el tratamiento completo de las especies exige considerar cada etapa por separado <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 16.6</a>)</span>. El ácido carbónico se ioniza en dos pasos, el primero con constante Ka1 y el segundo con Ka2, y el ion que es base conjugada en la primera etapa actúa como ácido en la segunda <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>. El ácido fosfórico, con tres hidrógenos ionizables, presenta tres constantes sucesivas que disminuyen marcadamente <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>.</p>
<p>La jerarquía de las constantes simplifica los cálculos: cuando Ka1 es mucho mayor que Ka2, la concentración de iones hidrógeno proviene casi por completo de la primera ionización, y la concentración de la especie producida en la segunda etapa resulta numéricamente igual a Ka2 <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 16.6</a>)</span>.</p>
<p>Para el ácido oxálico 0.10 M, cuya primera constante es 6.5 × 10⁻², la ecuación cuadrática completa da [H⁺] = 0.054 M, y la concentración del ion oxalato, C₂O₄²⁻, coincide con Ka2, 6.1 × 10⁻⁵ M <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>. La aproximación de una sola etapa fallaría aquí porque el 54% del ácido se ioniza, excediendo con mucho la regla del 5% <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>.</p>
<p>En una disolución de ácido fosfórico, las constantes decrecientes 7.5 × 10⁻³, 6.2 × 10⁻⁸ y 4.8 × 10⁻¹³ implican que la especie no ionizada es la más abundante, y solo el propio ácido y los iones H⁺ y H₂PO₄⁻ presentan concentración apreciable <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 16.6</a>)</span>. Para el ácido carbónico en disolución saturada de dióxido de carbono a 0.1 atmósferas, 0.0037 M <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 16.6</a>)</span>, la segunda etapa apenas contribuye al pH, y el ion carbonato queda fijado por Ka2, 5.6 × 10⁻¹¹ M <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 16.6</a>)</span>. Estos cálculos escalonados preparan el terreno para interpretar las curvas de valoración con múltiples puntos de equivalencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
</section>
<section id="el-producto-de-solubilidad-kps" class="level2">
<h2 class="anchored" data-anchor-id="el-producto-de-solubilidad-kps">El producto de solubilidad (Kps)</h2>
<p>Los equilibrios de solubilidad abordan una pregunta que las reglas cualitativas de preferencia no pueden responder: cuánto de un compuesto iónico poco soluble realmente se disuelve <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Una disolución saturada de cloruro de plata en contacto con el sólido constituye un equilibrio heterogéneo, y la actividad del sólido puro se toma como uno, de modo que la constante de equilibrio del proceso AgCl(s) ⇌ Ag⁺(aq) + Cl⁻(aq) se reduce al producto de las concentraciones iónicas <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Esta constante recibe el nombre de <span id="sec-producto-solubilidad"><strong>producto de solubilidad</strong></span>, Kps, y su expresión general eleva cada concentración al coeficiente estequiométrico <span class="citation" data-cites="chang2022 brown2012 pauling1988">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.4</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 13–5</a>)</span>.</p>
<p><span id="eq-kps"><span class="math display">\[K_{ps} = [\mathrm{M^{y+}}]^x [\mathrm{X^{x-}}]^y, \tag{18.2}\]</span></span></p>
<p>La ecuación (ec. <a href="#eq-kps" class="quarto-xref">Ecuación&nbsp;<span>18.2</span></a>) resume el producto de solubilidad para la sal general AxBy que se disocia en x cationes M^{y+} e y aniones X^{x-} <span class="citation" data-cites="chang2022 brown2012 pauling1988">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.4</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 13–5</a>)</span>. Cada concentración molar se eleva al número de iones de esa especie que produce una unidad fórmula, y el valor resultante, característico de cada sal a 25 °C, indica la solubilidad: cuanto menor es Kps, menos soluble es el compuesto <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Las comparaciones directas entre Kps solo son honestas para sales de estequiometría semejante, como AgCl y ZnS, o CaF₂ y Fe(OH)₂ <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>La <strong>solubilidad molar</strong> expresa la concentración de la disolución saturada en moles por litro, y la solubilidad en gramos por litro, y ambas se convierten entre sí con la masa molar <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Del Kps del bromuro de plata, 7.7 × 10⁻¹³, se obtiene una solubilidad molar de 8.8 × 10⁻⁷ M, pues cada unidad disuelta produce un ion de cada especie <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. En la dirección contraria, la solubilidad del sulfato de calcio, 0.67 g/L, conduce a un Kps de 2.4 × 10⁻⁵ después de convertir a moles <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>La utilidad práctica de estos equilibrios es inmediata: el esmalte dental se compone de hidroxiapatita, Ca₅(PO₄)₃OH, cuya disolución en medio ácido produce la caries, mientras que el sulfato de bario insoluble y opaco a los rayos X permite diagnosticar el tubo digestivo <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>La preparación industrial del carbonato de sodio y la formación de estalactitas y estalagmitas de carbonato de calcio son procesos de precipitación regidos por los mismos productos <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Pauling añade una observación pionera: el yodo se disuelve mucho mejor en disoluciones de yoduro porque forma el ion triyoduro, y el perclorato de potasio es menos soluble en presencia de su propio ion <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 13–5</a>)</span>.</p>
</section>
<section id="el-producto-iónico-y-la-predicción-de-precipitación" class="level2">
<h2 class="anchored" data-anchor-id="el-producto-iónico-y-la-predicción-de-precipitación">El producto iónico y la predicción de precipitación</h2>
<p>Las concentraciones de una disolución que no está en equilibrio se comparan con el producto de solubilidad mediante el <span id="sec-producto-ionico"><strong>producto iónico</strong></span>, Q, que tiene la misma forma que Kps pero usa las concentraciones iniciales <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. Para la mezcla de una disolución de iones plata con otra de iones cloruro, la expresión es Q = [Ag⁺]₀[Cl⁻]₀, donde el subíndice cero recuerda que no son concentraciones de equilibrio <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>Si Q es menor que Kps la disolución no está saturada y no precipita nada; si es igual, está exactamente saturada y existe equilibrio; y si es mayor, está sobresaturada y se forma precipitado hasta que el producto iónico vuelve a igualar a Kps <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>.</p>
<p><span id="eq-q-kps"><span class="math display">\[Q = [\mathrm{Ag^+}]_0 [\mathrm{Cl^-}]_0, \tag{18.3}\]</span></span></p>
<p>El criterio (ec. <a href="#eq-q-kps" class="quarto-xref">Ecuación&nbsp;<span>18.3</span></a>) sintetiza la predicción de precipitación en una sola comparación: cuando el producto iónico excede al producto de solubilidad, la precipitación ocurre <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. La condición de saturación se alcanza cuando Q iguala a Kps, y ninguna cantidad de sólido adicional puede disolverse <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Este umbral cuantitativo convierte la precipitación en una herramienta de separación, pues los iones pueden aislarse eligiendo un reactivo que forme con ellos sales de solubilidades muy distintas <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
<p>En una disolución que contiene iones plata y plomo, por ejemplo, la adición lenta de iones cloruro precipita primero el cloruro de plata, cuyo Kps es de 1.8 × 10⁻¹⁰, mientras que el cloruro de plomo, con Kps mucho mayor, permanece en disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. La concentración de cloruro necesaria para iniciar cada precipitación se calcula despejando en la expresión del producto: la sal menos soluble comienza antes y agota el ion común <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. Así, la plata puede separarse cuantitativamente del plomo controlando la adición del reactivo precipitante <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>.</p>
<p>Conviene registrar una discrepancia entre las tablas de las fuentes: Chang emplea un Kps de 1.6 × 10⁻¹⁰ para el cloruro de plata <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>, mientras que Brown cita 1.8 × 10⁻¹⁰ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. La diferencia afecta solo a la segunda cifra significativa y no altera el orden de precipitación, pues el cloruro de plata es mucho menos soluble que el de plomo con cualquiera de las dos cifras <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. Por coherencia con cada procedimiento, el capítulo emplea el valor de Brown en el ejemplo de separación plata-plomo y el de Chang en los cálculos de precipitación fraccionada <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
</section>
<section id="factores-que-alteran-la-solubilidad-ion-común-ph-e-iones-complejos" class="level2">
<h2 class="anchored" data-anchor-id="factores-que-alteran-la-solubilidad-ion-común-ph-e-iones-complejos">Factores que alteran la solubilidad: ion común, pH e iones complejos</h2>
<p>El efecto del ion común, introducido para los ácidos, actúa también sobre la solubilidad de las sales: la adición de un ion compartido desplaza el equilibrio de disolución hacia el sólido y reduce la cantidad disuelta <span class="citation" data-cites="chang2022 brown2012 pauling1988">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 13–5</a>)</span>. El cloruro de plata, cuya solubilidad en agua pura es de 1.9 × 10⁻³ g/L, se disuelve solo 3.6 × 10⁻⁶ g/L en una disolución 6.5 × 10⁻³ M de nitrato de plata, porque el ion plata común deprime la disolución <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. El valor de Kps permanece inalterado en ambos casos, pues es una constante de equilibrio, mientras que la solubilidad sí depende del entorno <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>El pH del medio altera la solubilidad de las sales cuyos aniones son bases conjugadas de ácidos débiles <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>)</span>. El hidróxido de magnesio, con Kps de 1.2 × 10⁻¹¹, tiene una disolución saturada de pH 10.45, y su solubilidad aumenta cuando el pH es menor porque los iones hidrógeno consumen el anión hidróxido <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. De modo análogo, el sulfuro de cobre(II) se disuelve mejor en medio ácido porque el ion sulfuro captura protones, mientras que la solubilidad del cloruro de plata no cambia con el pH, pues el ion cloruro es la base conjugada de un ácido fuerte <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>Los <span id="sec-iones-complejos"><strong>iones complejos</strong></span> forman una tercera vía para aumentar la solubilidad: un catión metálico se combina con bases de Lewis y retira el ion metálico de la disolución, desplazando el equilibrio hacia la disolución del sólido <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>)</span>. La tendencia a formar estos complejos se mide con la <span id="sec-constante-formacion"><strong>constante de formación</strong></span>, Kf, que cuantifica la estabilidad del ion complejo frente a su disociación <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>)</span>. La formación del complejo tetraminocobre(II), por ejemplo, explica que el hidróxido de cobre precipite primero al añadir amoniaco y se redisuelva después en exceso del mismo reactivo <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p><span id="eq-kf"><span class="math display">\[K_f = \frac{[\mathrm{Cu(NH_3)_4^{2+}}]}{[\mathrm{Cu^{2+}}][\mathrm{NH_3}]^4}, \tag{18.4}\]</span></span></p>
<p>La expresión (ec. <a href="#eq-kf" class="quarto-xref">Ecuación&nbsp;<span>18.4</span></a>) define la constante de formación para el complejo Cu(NH₃)₄²⁺: en el numerador figura la concentración del ion complejo y en el denominador el producto de la concentración del catión libre por la del ligando elevada a cuatro, su coeficiente estequiométrico <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>El valor muy grande de Kf indica que el complejo es muy estable y que la concentración de iones cobre libres en el equilibrio es extremadamente pequeña <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. Un caso cuantitativamente impresionante es el cloruro de plata: su solubilidad molar en agua pura es 1.3 × 10⁻⁵ M, pero en amoniaco 1.0 M alcanza 0.045 M gracias a la formación de Ag(NH₃)₂⁺, una multiplicación por más de tres mil <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>Ciertos hidróxidos, llamados <span id="sec-amfoteros"><strong>amfóteros</strong></span>, reaccionan tanto con ácidos como con bases, y su solubilidad crece en ambos extremos del pH <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>)</span>. El hidróxido de aluminio, el de plomo(II), el de cromo(III), el de zinc y el de cadmio pertenecen a esta clase <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. El aumento de solubilidad del Al(OH)₃ en medio básico se debe a la formación del ion complejo Al(OH)₄⁻, donde el hidróxido actúa como ácido de Lewis y el ion hidróxido como base de Lewis <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.5</a>)</span>.</p>
</section>
<section id="precipitación-fraccionada-y-análisis-cualitativo" class="level2">
<h2 class="anchored" data-anchor-id="precipitación-fraccionada-y-análisis-cualitativo">Precipitación fraccionada y análisis cualitativo</h2>
<p>La <span id="sec-precipitacion"><strong>precipitación fraccionada</strong></span> separa iones de solubilidades distintas precipitándolos uno tras otro con la adición controlada de un reactivo común <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. En una disolución que contiene iones cloruro y bromuro, ambos 0.020 M, la adición lenta de nitrato de plata inicia primero la precipitación del bromuro de plata, cuyo Kps de 7.7 × 10⁻¹³ exige superar apenas [Ag⁺] = 3.9 × 10⁻¹¹ M, mientras que el cloruro de plata, con Kps de 1.6 × 10⁻¹⁰, necesita [Ag⁺] = 8.0 × 10⁻⁹ M <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>. Entre esos dos límites, el ion bromuro precipita casi por completo mientras el cloruro permanece en disolución <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
<p>La eficacia de la separación es cuantificable: cuando la concentración de plata alcanza el umbral del cloruro, quedan solo 0.48% de los iones bromuro originales, es decir, 99.52% han precipitado como bromuro de plata <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>. El procedimiento se generaliza a más de dos iones siempre que sus sales presenten productos de solubilidad suficientemente distintos <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.6</a>)</span>. Así, los haluros de plata precipitan en el orden yoduro, bromuro, cloruro, de menor a mayor Kps <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
<p>El <span id="sec-analisis-cualitativo"><strong>análisis cualitativo</strong></span> aprovecha estas diferencias para identificar los iones presentes en una muestra desconocida, mediante un esquema sistemático de precipitación y separación de cationes en cinco grupos <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>. El primer grupo precipita con ácido clorhídrico diluido, pues solo los iones Ag⁺, Hg₂²⁺ y Pb²⁺ forman cloruros insolubles; los demás permanecen en disolución <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>. El segundo grupo se precipita con sulfuro de hidrógeno en medio ácido, donde la concentración del ion sulfuro es mínima, y solo los sulfuros menos solubles, como Bi₂S₃, CdS, CuS, HgS y SnS, se depositan <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>.</p>
<p>Al hacer básica la disolución con hidróxido de sodio, el equilibrio del sulfuro se desplaza y precipitan los sulfuros más solubles, CoS, FeS, MnS, NiS y ZnS, junto con los hidróxidos de aluminio y de cromo <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>. El cuarto grupo se separa con carbonato de sodio, que precipita los iones Ba²⁺, Ca²⁺ y Sr²⁺ como carbonatos, y en el quinto quedan solo los iones Na⁺, K⁺ y NH₄⁺ <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>.</p>
<p>La presencia de amonio se confirma porque el hidróxido de sodio libera amoniaco gaseoso, detectado por su olor o por el viraje del papel de tornasol, y los metales alcalinos por la <span id="sec-prueba-llama"><strong>prueba de llama</strong></span>, que da color amarillo al sodio, violeta al potasio y verde al cobre <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>.</p>
<p>La secuencia no es arbitraria, pues cada etapa debe eliminar por completo los iones del grupo anterior para no contaminar los siguientes <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.7</a>)</span>. Si el clorhídrico no eliminara todo el plomo del primer grupo, por ejemplo, este precipitaría después como sulfuro y falsearía el diagnóstico <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>)</span>. Los reactivos se eligen para precipitar el menor número de cationes posible, garantizando así que cada grupo quede definido por un reactivo específico <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.8</a>)</span>.</p>
</section>
<section id="ejemplo-resuelto" class="level2">
<h2 class="anchored" data-anchor-id="ejemplo-resuelto">Ejemplo resuelto</h2>
<p>Se prepara un tampón disolviendo 0.200 mol de ácido acético y 0.200 mol de acetato de sodio en agua hasta completar 0.500 L de disolución, y se agregan después 10.0 mL de hidróxido de sodio 2.0 M; el objetivo es observar cuánto se mueve el pH frente a esa adición <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>La primera parte del cálculo es estequiométrica: los 0.020 mol de iones hidróxido reaccionan por completo con el ácido débil, consumiendo 0.020 mol de ácido acético y generando 0.020 mol adicionales de acetato <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Tras la reacción quedan 0.180 mol de ácido y 0.220 mol de base conjugada en un volumen total de 0.510 L, y como el volumen se cancela en el cociente, puede trabajarse con moles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>La segunda parte es el equilibrio: introduciendo las cantidades ajustadas en la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>) con pKa del acético igual a 4.74, el pH resulta 4.74 + log(0.220/0.180) = 4.83 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El cambio respecto del tampón original, con pH 4.74, es de solo 0.09 unidades, pese a haber añadido una cantidad de base que en agua pura produciría un efecto mucho mayor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Si los mismos 0.020 mol de hidróxido se disolvieran en 0.510 L de agua pura, la concentración de iones hidróxido sería 0.039 M, el pOH 1.41 y el pH 12.59 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>La comparación entre 4.83 y 12.59 condensa toda la teoría de este capítulo: el tampón absorbe el impacto del hidróxido convirtiéndolo en acetato, mientras que el agua carece de reserva alguna <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. La capacidad del tampón se agotaría solo si se añadiera tanto hidróxido que el ácido acético se consumiera por completo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El ejemplo ilustra además la estrategia general de dos pasos, estequiometría primero y equilibrio después, que gobierna también las valoraciones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
</section>
<section id="preguntas-y-ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="preguntas-y-ejercicios">Preguntas y ejercicios</h2>
<p>Los ejercicios de esta sección se inspiran en la tipología de <span class="citation" data-cites="brown2012">Brown et&nbsp;al. (<a href="../references.html#ref-brown2012" role="doc-biblioref">2012</a>)</span> (cap. 17), <span class="citation" data-cites="chang2022">Chang y Overby (<a href="../references.html#ref-chang2022" role="doc-biblioref">2022</a>)</span> (cap. 16) y <span class="citation" data-cites="pauling1988">Pauling (<a href="../references.html#ref-pauling1988" role="doc-biblioref">1988</a>)</span> (caps. 13-14); los valores, las especies y los contextos numéricos son originales de este libro, y cada resultado del solucionario ha sido verificado por re-resolución independiente.</p>
<p>Calcule el pH de una disolución 0.25 M de ácido acético y el de otra disolución que sea 0.25 M en ácido acético y 0.40 M en acetato de sodio, empleando para ambas la constante Ka = 1.8 × 10⁻⁵, y compare los resultados con lo que predice la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>) <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>.</p>
<p>Prepare un tampón disolviendo 0.150 mol de amoniaco y 0.150 mol de cloruro de amonio en un litro de agua y añada después 0.030 mol de ácido clorhídrico, indicando qué reacción consume el ácido añadido y calculando el pH final con la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>), sabiendo que el pKb del amoniaco es 4.74 <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>.</p>
<p>Determine el rango de pH en el que un tampón de ácido láctico-lactato resulta eficaz, sabiendo que la constante Ka del ácido láctico es de 1.4 × 10⁻⁴, y explique por qué fuera de ese margen la resistencia al cambio se deteriora <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Compare dos tampones de acetato, uno 2.0 M en ácido acético y 2.0 M en acetato de sodio y otro 0.20 M en ambos componentes, calculando el pH de cada uno y discutiendo cuál neutralizará más ácido o base antes de cambiar su pH de forma apreciable <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>)</span>.</p>
<p>Calcule el pH en el punto de equivalencia de la valoración de 30.0 mL de ácido fórmico 0.10 M con hidróxido de potasio 0.10 M, considerando que la sal formada se hidroliza como base débil y empleando la relación Kb = Kw/Ka derivada en el capítulo anterior <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.3</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Un indicador tiene una constante de ionización de 2.0 × 10⁻⁶, con su forma no ionizada de un color y la ionizada de otro; calcule el pKa del indicador y el pH al que mostrará el cambio de color, y explique el criterio para elegirlo en una valoración <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>)</span>.</p>
<p>Determine las concentraciones de equilibrio de las principales especies de una disolución 0.10 M de ácido fosfórico, resolviendo la primera etapa con la ecuación cuadrática completa y aplicando la regla de que la especie de la segunda etapa iguala a Ka2 cuando Ka1 domina <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>.</p>
<p>Calcule el producto de solubilidad del cromato de plomo(II) a partir de su solubilidad, 4.5 × 10⁻⁵ g/L, convirtiendo primero a moles por litro con la masa molar de 323.2 g/mol y elevando después al cuadrado la solubilidad molar de la sal <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>Calcule la solubilidad del bromuro de plata en agua pura y en una disolución 0.0010 M de bromuro de sodio, empleando Kps = 7.7 × 10⁻¹³, y exprese ambos resultados en gramos por litro para comparar el efecto del ion común observado <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>Una disolución contiene iones cloruro y bromuro, ambos 0.020 M, y sobre ella se añade lentamente nitrato de plata; calcule la concentración de iones plata necesaria para iniciar la precipitación de cada haluro y el porcentaje de bromuro que permanece sin precipitar cuando comienza a precipitar el cloruro <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
</section>
<section id="solucionario" class="level2">
<h2 class="anchored" data-anchor-id="solucionario">Solucionario</h2>
<p>La disolución 0.25 M de ácido acético solo plantea la cuadrática x²/(0.25 − x) = 1.8 × 10⁻⁵, cuya aproximación x = 2.1 × 10⁻³ M verifica la regla del 5%, y conduce a pH = 2.67 <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. Con acetato de sodio 0.40 M, el ion común suprime la ionización y la ecuación (ec. <a href="#eq-henderson-hasselbalch" class="quarto-xref">Ecuación&nbsp;<span>18.1</span></a>) da pH = 4.74 + log(0.40/0.25) = 4.94 <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>)</span>. El ion común eleva el pH en más de dos unidades al desplazar el equilibrio hacia la izquierda <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.1</a>)</span>.</p>
<p>El ácido clorhídrico añadido, 0.030 mol, reacciona con el amoniaco del tampón y lo convierte en ion amonio, dejando 0.120 mol de la base y 0.180 mol del ácido conjugado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El pKa del ion amonio vale 14.00 − 4.74 = 9.26, y el pH final es 9.26 + log(0.120/0.180) = 9.08, apenas 0.18 unidades por debajo del pH inicial de 9.26 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. En agua pura, los mismos 0.030 mol de ácido producirían un pH de 1.52; el tampón los absorbe casi sin moverse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>El pKa del ácido láctico es −log(1.4 × 10⁻⁴) = 3.85, y el rango eficaz del tampón abarca pH = 3.85 ± 1, es decir, de 2.85 a 4.85 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Fuera de ese margen, un componente supera al otro en más de un factor diez, el logaritmo del cociente crece o decrece más de una unidad y la resistencia al cambio se pierde <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Por eso los manuales recomiendan elegir el par cuyo pKa esté a menos de una unidad del pH que se desea fijar <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Ambos tampones tienen pH 4.74, porque el pH solo depende del cociente de concentraciones y en los dos el cociente vale uno <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. El tampón 2.0 M posee, sin embargo, una capacidad amortiguadora diez veces mayor, pues contiene diez veces más moles de ácido y de base capaces de absorber las adiciones <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.2</a>)</span>. La capacidad depende de las cantidades absolutas de reserva, y la resistencia relativa al pH del cociente <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–7</a>)</span>.</p>
<p>En el punto de equivalencia, 30.0 mL de ácido fórmico 0.10 M han reaccionado con el mismo volumen de hidróxido de potasio 0.10 M, formando formiato de potasio 0.050 M en el volumen doblado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. La base conjugada del fórmico tiene Kb = 1.0 × 10⁻¹⁴ / 1.8 × 10⁻⁴ = 5.6 × 10⁻¹¹, y la hidrólisis produce [OH⁻] = 1.7 × 10⁻⁶ M, de donde pOH = 5.78 y pH = 8.22 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. El pH supera 7 porque el formiato es una base débil, igual que sucede con cualquier sal de ácido débil y base fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>El pKa del indicador es −log(2.0 × 10⁻⁶) = 5.70, y el cambio de color ocurre en ese pH, donde las formas HIn e In⁻ se igualan <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>)</span>. El indicador resulta idóneo para valoraciones cuyo punto de equivalencia caiga cerca de 5.70, como la de una base débil con un ácido fuerte, y desaconsejable cuando el salto de pH ocurra en otra zona <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.4</a>)</span>. El color observado depende del desplazamiento del equilibrio HIn ⇌ H⁺ + In⁻ por el pH del medio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Para el ácido fosfórico 0.10 M, la primera etapa plantea x² + 7.5 × 10⁻³ x − 7.5 × 10⁻⁴ = 0, cuya raíz positiva es x = 0.024 M, pues la aproximación simple excedería la regla del 5% <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>. Entonces [H⁺] = [H₂PO₄⁻] = 0.024 M, el pH vale 1.62, y la concentración de HPO₄²⁻ iguala a Ka2 = 6.2 × 10⁻⁸ M <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>. La tercera especie, PO₄³⁻, queda en concentraciones insignificantes por la pequeñez de Ka3 <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>)</span>.</p>
<p>La solubilidad molar del cromato de plomo(II) es 4.5 × 10⁻⁵ g/L ÷ 323.2 g/mol = 1.4 × 10⁻⁷ M, y su producto de solubilidad, siendo la sal 1:1, es el cuadrado, 2.0 × 10⁻¹⁴ <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. Convertir la solubilidad en gramos por litro a moles por litro es el paso indispensable, pues Kps se define con concentraciones molares <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>. La pequeñez del resultado confirma que el cromato de plomo es una sal muy poco soluble <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>En agua pura, la solubilidad molar del bromuro de plata es √(7.7 × 10⁻¹³) = 8.8 × 10⁻⁷ M, que multiplicada por la masa molar de 187.8 g/mol da 1.7 × 10⁻⁴ g/L <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. En bromuro de sodio 0.0010 M, el ion común reduce la solubilidad a 7.7 × 10⁻¹⁰ M, es decir, 1.4 × 10⁻⁷ g/L, casi mil veces menor <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. La comparación muestra que el ion común desplaza el equilibrio hacia la izquierda sin alterar el valor de Kps <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>.</p>
<p>Para el bromuro de plata, la precipitación se inicia cuando [Ag⁺] = 7.7 × 10⁻¹³ / 0.020 = 3.9 × 10⁻¹¹ M, y para el cloruro cuando [Ag⁺] = 1.6 × 10⁻¹⁰ / 0.020 = 8.0 × 10⁻⁹ M <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>. En el intervalo entre ambos umbrales, manteniendo la concentración de plata por debajo de 8.0 × 10⁻⁹ M, el bromuro precipita casi por entero <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>. Cuando el cloruro empieza a precipitar, el bromuro restante es 7.7 × 10⁻¹³ / 8.0 × 10⁻⁹ = 9.6 × 10⁻⁵ M, el 0.48% del valor inicial, de modo que 99.52% del bromuro ya se ha separado <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6</a>)</span>.</p>
</section>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>El efecto del ion común mostró cómo un ion compartido por dos solutos suprime la ionización del ácido o la base débil, y dio lugar a la ecuación de Henderson-Hasselbalch, que liga el pH con el pKa y con el cociente de las concentraciones del par conjugado <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.1</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>.</p>
<p>Los tampones, mezclas de un ácido débil con su base conjugada, resisten el cambio de pH gracias a esa reserva de especies, y su capacidad y su rango eficaz, pH = pKa ± 1, guían su diseño <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.2</a>)</span>. Las valoraciones convierten la neutralización en medida, y sus curvas revelan la fuerza de las especies y la posición del punto de equivalencia <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>.</p>
<p>Los indicadores, ácidos débiles coloreados, señalan el punto final cuando su pKa coincide con el pH de equivalencia, criterio central para elegir entre fenolftaleína y rojo de metilo <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 14–6</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. Los ácidos polipróticos se tratan por etapas, con la regla de que la segunda especie iguala a Ka2 cuando la primera constante domina, y sus curvas muestran varios puntos de equivalencia <span class="citation" data-cites="chang2022 brown2012">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 15.8</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 17.3</a>)</span>. El producto de solubilidad cuantificó la disolución de las sales poco solubles, y su comparación con el producto iónico decide si precipita un sólido <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.5</a>)</span>.</p>
<p>La solubilidad se altera con el ion común, con el pH cuando el anión es base conjugada de un ácido débil, y con la formación de iones complejos, cuya constante de formación explica redisolución de precipitados como el cloruro de plata en amoniaco <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.7</a>)</span>. La precipitación fraccionada y el análisis cualitativo en cinco grupos aplican estas ideas a la separación e identificación de cationes <span class="citation" data-cites="chang2022">(<a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 16.6, 16.8</a>)</span>. Este arsenal de equilibrios deja preparado el terreno para la termodinámica, que explicará por qué estos procesos ocurren en la dirección que ocurren <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 17</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-brown2012" class="csl-entry" role="listitem">
Brown, Theodore L., H. Eugene LeMay, Bruce E. Bursten, Catherine J. Murphy, y Patrick M. Woodward. 2012. <em>Chemistry: The Central Science</em>. 12th ed. Pearson Prentice Hall.
</div>
<div id="ref-chang2022" class="csl-entry" role="listitem">
Chang, Raymond, y Jason Overby. 2022. <em>Chemistry</em>. 14th (ISE). McGraw-Hill Education.
</div>
<div id="ref-pauling1988" class="csl-entry" role="listitem">
Pauling, Linus. 1988. <em>General Chemistry</em>. 3rd (reprinted). Dover Publications.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../02_quimica/16-acidos-y-bases.html" class="pagination-link" aria-label="Ácidos y bases">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Ácidos y bases</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../02_quimica/18-termodinamica-quimica.html" class="pagination-link" aria-label="Termodinámica química">
        <span class="nav-page-text"><span class="chapter-title">Termodinámica química</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>