<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Electroquímica – Nous</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../02_quimica/20-quimica-nuclear.html" rel="next">
<link href="../02_quimica/18-termodinamica-quimica.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-53aca5cea238aca1de29c5a91d105b8d.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../site_libs/bootstrap/bootstrap-28c86cf0d638d21149957566e6a88f2f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No se han encontrado resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title"><span class="chapter-title">Electroquímica</span></h1>
        </a>     
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../">Nous</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="../Nous.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Alternar modo oscuro"><i class="bi"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Nous</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Conjuntos</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../01_conjuntos/00_proposicion_negacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Proposición y su negación</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Química</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/01-historia-de-la-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 1 · La química en la historia</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/02-materia-y-medicion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 2 · La materia y su medición</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/03-atomos-moleculas-e-iones.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Capítulo 3 · Átomos, moléculas e iones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/04-estequiometria.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estequiometría: moles, fórmulas y ecuaciones químicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/05-reacciones-en-disolucion-acuosa.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Reacciones en disolución acuosa</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/06-estructura-electronica-del-atomo.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Estructura electrónica del átomo</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/07-tabla-periodica-y-propiedades-periodicas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tabla periódica y propiedades periódicas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/08-enlace-quimico-i-conceptos-fundamentales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Enlace químico I: conceptos fundamentales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/09-enlace-quimico-ii-geometria-molecular-y-teorias-de-enlace.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Enlace químico II: geometría molecular y teorías de enlace</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/10-gases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Gases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/11-termoquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Termoquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/12-liquidos-fuerzas-intermoleculares-y-solidos.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Líquidos, fuerzas intermoleculares y sólidos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/13-disoluciones-y-propiedades-coligativas.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Disoluciones y propiedades coligativas</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/14-cinetica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Cinética química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/15-equilibrio-quimico.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Equilibrio químico</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/16-acidos-y-bases.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Ácidos y bases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/17-equilibrios-acido-base-y-solubilidad.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Equilibrios ácido-base y de solubilidad: aplicaciones</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/18-termodinamica-quimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Termodinámica química</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/19-electroquimica.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Electroquímica</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/20-quimica-nuclear.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química nuclear</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/21-quimica-de-los-no-metales.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química de los no metales</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/22-quimica-de-los-metales-de-transicion-y-quimica-de-coordinacion.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química de los metales de transición y química de coordinación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/23-quimica-organica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química orgánica: la química de los compuestos del carbono</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/24-bioquimica.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Bioquímica: la química de la vida</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/25-quimica-del-ambiente.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Química del ambiente: atmósfera, agua y química verde</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../02_quimica/26-quimica-moderna-tecnicas-y-fronteras.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">La química moderna: técnicas, logros y fronteras</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Biología</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../03_biologia/01_base_fisica_herencia.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">La base física de la herencia</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Apéndices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Alternar sección">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción">Introducción</a></li>
  <li><a href="#de-la-combinación-con-oxígeno-a-la-transferencia-de-electrones" id="toc-de-la-combinación-con-oxígeno-a-la-transferencia-de-electrones" class="nav-link" data-scroll-target="#de-la-combinación-con-oxígeno-a-la-transferencia-de-electrones">De la combinación con oxígeno a la transferencia de electrones</a></li>
  <li><a href="#balanceo-redox-por-el-método-de-las-semirreacciones" id="toc-balanceo-redox-por-el-método-de-las-semirreacciones" class="nav-link" data-scroll-target="#balanceo-redox-por-el-método-de-las-semirreacciones">Balanceo redox por el método de las semirreacciones</a></li>
  <li><a href="#celdas-voltaicas-separar-la-oxidación-de-la-reducción" id="toc-celdas-voltaicas-separar-la-oxidación-de-la-reducción" class="nav-link" data-scroll-target="#celdas-voltaicas-separar-la-oxidación-de-la-reducción">Celdas voltaicas: separar la oxidación de la reducción</a></li>
  <li><a href="#potencial-de-celda-y-la-escala-de-los-potenciales-estándar" id="toc-potencial-de-celda-y-la-escala-de-los-potenciales-estándar" class="nav-link" data-scroll-target="#potencial-de-celda-y-la-escala-de-los-potenciales-estándar">Potencial de celda y la escala de los potenciales estándar</a></li>
  <li><a href="#energía-libre-trabajo-eléctrico-y-constante-de-equilibrio" id="toc-energía-libre-trabajo-eléctrico-y-constante-de-equilibrio" class="nav-link" data-scroll-target="#energía-libre-trabajo-eléctrico-y-constante-de-equilibrio">Energía libre, trabajo eléctrico y constante de equilibrio</a></li>
  <li><a href="#la-ecuación-de-nernst-y-las-celdas-de-concentración" id="toc-la-ecuación-de-nernst-y-las-celdas-de-concentración" class="nav-link" data-scroll-target="#la-ecuación-de-nernst-y-las-celdas-de-concentración">La ecuación de Nernst y las celdas de concentración</a></li>
  <li><a href="#baterías-y-celdas-de-combustible" id="toc-baterías-y-celdas-de-combustible" class="nav-link" data-scroll-target="#baterías-y-celdas-de-combustible">Baterías y celdas de combustible</a></li>
  <li><a href="#corrosión-la-descarga-espontánea-de-los-metales" id="toc-corrosión-la-descarga-espontánea-de-los-metales" class="nav-link" data-scroll-target="#corrosión-la-descarga-espontánea-de-los-metales">Corrosión: la descarga espontánea de los metales</a></li>
  <li><a href="#electrólisis-y-electrometalurgia" id="toc-electrólisis-y-electrometalurgia" class="nav-link" data-scroll-target="#electrólisis-y-electrometalurgia">Electrólisis y electrometalurgia</a></li>
  <li><a href="#ejemplo-resuelto-la-celda-de-zinc-y-cobre-bajo-condiciones-reales" id="toc-ejemplo-resuelto-la-celda-de-zinc-y-cobre-bajo-condiciones-reales" class="nav-link" data-scroll-target="#ejemplo-resuelto-la-celda-de-zinc-y-cobre-bajo-condiciones-reales">Ejemplo resuelto: la celda de zinc y cobre bajo condiciones reales</a></li>
  <li><a href="#preguntas-y-ejercicios" id="toc-preguntas-y-ejercicios" class="nav-link" data-scroll-target="#preguntas-y-ejercicios">Preguntas y ejercicios</a></li>
  <li><a href="#solucionario" id="toc-solucionario" class="nav-link" data-scroll-target="#solucionario">Solucionario</a></li>
  <li><a href="#resumen" id="toc-resumen" class="nav-link" data-scroll-target="#resumen">Resumen</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-title">Electroquímica</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">Introducción</h2>
<p>Las reacciones de oxidación-reducción ya aparecieron en el capítulo 5 (<span class="quarto-unresolved-ref">?sec-oxido-reduccion-intro</span>) como la tercera gran clase de reacciones en disolución acuosa, y el capítulo 18 entregó el criterio termodinámico para decidir su espontaneidad <span class="citation" data-cites="brown2012 chang2022">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 4.4</a>; <a href="../references.html#ref-chang2022" role="doc-biblioref">Chang y Overby 2022, sec. 17.4</a>)</span>. Este capítulo cierra el círculo mostrando que la energía libre de esas reacciones puede transformarse en energía eléctrica, trabajo útil que se mide en voltios y viaja por cables <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 20</a>)</span>. La <strong>electroquímica</strong> estudia, así, el puente entre los electrones que se intercambian y la electricidad que se aprovecha <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>.</p>
<p>El puente tiene historia: el electrón lo descubrió Joseph John Thomson en 1897, y Michael Faraday (1791–1867) lo domeñó antes de que existiera su nombre, al punto de que Atkins lo llama el arquero cambiador de electrones <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>. Faraday cuantificó las leyes de la electrólisis, y su apellido bautiza la constante que liga la carga eléctrica con los moles de electrones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>. La fabricación del acero, la corrosión de los metales y la fotosíntesis comparten este mismo lenguaje de transferencia electrónica <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>.</p>
<p>La oxidación y la reducción son inseparables, como advierte Oriakhi: una no puede ocurrir sin la otra, del mismo modo que una mano no aplaude sola <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 22.1</a>)</span>. Los electrones cedidos por la especie que se oxida son ganados exactamente por la que se reduce, y esa contabilidad permite explotar la reacción en dispositivos que van de la batería del automóvil al marcapasos <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.1</a>)</span>. El recorrido del capítulo abarcará el balanceo por semirreacciones, las celdas voltaicas, la ecuación de Nernst, las baterías, la corrosión y la electrólisis <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 20</a>)</span>.</p>
</section>
<section id="de-la-combinación-con-oxígeno-a-la-transferencia-de-electrones" class="level2">
<h2 class="anchored" data-anchor-id="de-la-combinación-con-oxígeno-a-la-transferencia-de-electrones">De la combinación con oxígeno a la transferencia de electrones</h2>
<p>El nombre «oxidación» nació para designar la combinación de una sustancia con el oxígeno, como en la combustión del magnesio, 2Mg + O₂ → 2MgO <span class="citation" data-cites="atkins2015 oriakhi2021">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 22.2</a>)</span>. Pronto se advirtió que la misma cesión de electrones ocurría sin oxígeno: el magnesio también arde en cloro formando MgCl₂, y en ambos casos cede dos electrones <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>. La oxidación se generalizó entonces como la pérdida de electrones, y la reducción, ya definida en el capítulo 5, como su ganancia en el sentido inverso <span class="citation" data-cites="atkins2015 brown2012">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>.</p>
<p>Oriakhi clasifica las oxidaciones según el mecanismo aparente: adición de oxígeno, combinación con un elemento más electronegativo, pérdida de hidrógeno o pérdida directa de electrones <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 22.2</a>)</span>. La reacción H₂S + Cl₂ → 2HCl + S ilustra la tercera vía, pues el azufre pierde sus hidrógenos, y la transformación 2FeCl₂ + Cl₂ → 2FeCl₃ la cuarta, con cada ion hierro cediendo un electrón <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 22.2</a>)</span>. En todos los casos, la especie que pierde electrones actúa como <strong>agente reductor</strong> y la que los gana como <strong>agente oxidante</strong> <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>.</p>
<p>La transferencia de electrones arrastra consigo átomos, y esa tracción explica procesos a gran escala: la siderurgia reduce el hierro de sus óxidos, la fotosíntesis encadena reacciones redox para construir carbohidratos y la respiración degrada los alimentos como una corrosión orgánica <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>. La misma química permite extraer aluminio, purificar cobre y cromar piezas, aplicaciones que se retomarán en la electrólisis <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>. El número de oxidación, aprendido en el capítulo 5, será la herramienta contable para seguirles la pista a los electrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>.</p>
</section>
<section id="balanceo-redox-por-el-método-de-las-semirreacciones" class="level2">
<h2 class="anchored" data-anchor-id="balanceo-redox-por-el-método-de-las-semirreacciones">Balanceo redox por el método de las semirreacciones</h2>
<p>El capítulo 5 balanceó ecuaciones redox sencillas por tanteo, pero las reacciones complejas exigen un método sistemático: descomponer la ecuación en dos <span id="sec-reacciones-redox"><strong>semirreacciones</strong></span>, una de oxidación y otra de reducción, que se balancean por separado y luego se combinan <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. El balance de masa y de carga de cada semirreacción es la clave del procedimiento, y en medio ácido se ajusta con iones H⁺ y moléculas de agua <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. Primero se igualan los electrones de ambas y después se suman cancelando lo común <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>En medio ácido, el permanganato oxida al ion oxalato: el MnO₄⁻ se reduce a Mn²⁺ ganando cinco electrones mientras el C₂O₄²⁻ se oxida a CO₂ perdiendo dos por cada ion <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. Multiplicando cada semirreacción para igualar diez electrones y sumando se obtiene la ecuación neta:</p>
<p><span id="eq-mno4-oxalato"><span class="math display">\[2\mathrm{MnO}_4^- + 5\mathrm{C}_2\mathrm{O}_4^{2-} + 16\mathrm{H}^+ \rightarrow 2\mathrm{Mn}^{2+} + 10\mathrm{CO}_2 + 8\mathrm{H}_2\mathrm{O} \tag{20.1}\]</span></span></p>
<p>En la ecuación balanceada (<a href="#eq-mno4-oxalato" class="quarto-xref">Ecuación&nbsp;<span>20.1</span></a>), el permanganato aporta los cinco electrones que necesita cada ion manganeso y el oxalato los diez que cede entre los cinco iones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. Los dieciséis protones y las ocho moléculas de agua ajustan la carga y el oxígeno del medio ácido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. En medio básico el método se adapta ajustando primero con agua y desplazando protones con iones hidróxido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>El método exige reconocer el cambio de número de oxidación para identificar qué se oxida y qué se reduce <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 22.3</a>)</span>. En la ecuación (<a href="#eq-mno4-oxalato" class="quarto-xref">Ecuación&nbsp;<span>20.1</span></a>), el manganeso pasa de +7 a +2 y el carbono de +3 a +4, y esos cambios fijan la estequiometría de los electrones transferidos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. Cuando la misma sustancia se oxida y se reduce a la vez, la reacción se llama de desproporción y el método se aplica igualmente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 20</a>, ej. 20.97)</span>. Dominar este balanceo prepara la construcción de celdas, donde cada semirreacción ocurre en un electrodo distinto <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
</section>
<section id="celdas-voltaicas-separar-la-oxidación-de-la-reducción" class="level2">
<h2 class="anchored" data-anchor-id="celdas-voltaicas-separar-la-oxidación-de-la-reducción">Celdas voltaicas: separar la oxidación de la reducción</h2>
<p>Una reacción redox espontánea libera energía que, si la oxidación y la reducción ocurren en el mismo recipiente, se disipa como calor <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. Separando ambas semirreacciones en <strong>semiceldas</strong> conectadas por un conductor externo, los electrones deben recorrer ese circuito y su flujo constituye corriente eléctrica <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. El dispositivo que logra esta separación se llama <strong>celda voltaica</strong> o <span id="sec-celdas-voltaicas"><strong>celda galvánica</strong></span>, y en él la reacción espontánea genera electricidad <span class="citation" data-cites="brown2012 oriakhi2021">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.1</a>)</span>.</p>
<p>En la celda clásica de zinc y cobre, una lámina de Zn se sumerge en disolución de ZnSO₄ y otra de Cu en CuSO₄, unidas por un <strong>puente salino</strong> que contiene un electrolito inerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. El zinc se oxida cediendo electrones a su lámina, que los conduce por el alambre externo hasta el cobre, donde el Cu²⁺ los acepta y se deposita como metal <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. La reacción neta,</p>
<p><span id="eq-celda-zinc-cobre"><span class="math display">\[\mathrm{Zn}(s) + \mathrm{Cu}^{2+}(aq) \rightarrow \mathrm{Zn}^{2+}(aq) + \mathrm{Cu}(s) \tag{20.2}\]</span></span></p>
<p>La ecuación (<a href="#eq-celda-zinc-cobre" class="quarto-xref">Ecuación&nbsp;<span>20.2</span></a>) es la misma reacción redox espontánea del capítulo 5, ahora domesticada para producir trabajo eléctrico en lugar de calor <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.1</a>)</span>. Toda la estequiometría del capítulo 5 se conserva: un átomo de zinc reacciona con un ion cúprico para dar un ion zinc disuelto y un átomo de cobre metálico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>.</p>
<p>El <strong>electrodo</strong> donde ocurre la oxidación se llama <strong>ánodo</strong> y el donde ocurre la reducción, <strong>cátodo</strong>; en la celda de la ecuación (<a href="#eq-celda-zinc-cobre" class="quarto-xref">Ecuación&nbsp;<span>20.2</span></a>) el zinc es el ánodo y el cobre el cátodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. El puente salino cierra el circuito iónico: los cationes migran hacia el cátodo y los aniones hacia el ánodo, manteniendo la neutralidad de ambas disoluciones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>. Por el circuito externo los electrones fluyen siempre del ánodo al cátodo, y el voltímetro registra unos 1.10 V para esta celda <span class="citation" data-cites="brown2012 oriakhi2021">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.1</a>)</span>.</p>
<p>La serie de actividad del capítulo 5 anticipa estas transferencias: un metal más activo desplaza al menos activo de su disolución <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. El zinc, por encima del cobre en la serie, se oxida espontáneamente ante el Cu²⁺, mientras el cobre sumergido en disolución de Zn²⁺ no deposita zinc sino que alcanza un equilibrio con una proporción diminuta de concentraciones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–5</a>)</span>. Pauling enfatiza que esa misma relación de equilibrio se alcanza desde cualquiera de los dos sentidos, evidencia de que la tendencia termodinámica se mide con la celda y no se decide por inspección <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–5</a>)</span>.</p>
</section>
<section id="potencial-de-celda-y-la-escala-de-los-potenciales-estándar" class="level2">
<h2 class="anchored" data-anchor-id="potencial-de-celda-y-la-escala-de-los-potenciales-estándar">Potencial de celda y la escala de los potenciales estándar</h2>
<p>El <strong>potencial de celda</strong>, también llamado <strong>fuerza electromotriz (fem)</strong>, mide la diferencia de potencial eléctrico entre los electrodos y cuantifica la tendencia de los electrones a fluir <span class="citation" data-cites="brown2012 oriakhi2021">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.2</a>)</span>. Un voltio equivale a un julio por coulomb, 1 V = 1 J/C, de modo que el voltaje expresa la energía eléctrica por unidad de carga <span class="citation" data-cites="oriakhi2021">(<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.2</a>)</span>. El potencial depende de la concentración, la presión y la temperatura, y por eso se define un estado estándar convencional <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>El <strong>electrodo estándar de hidrógeno (EEH)</strong> fija el cero de la escala: platino en contacto con H₂ gaseoso a 1 atm e iones H⁺ a 1 M <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Todo electrodo se mide frente a este patrón, y el valor obtenido es su <span id="sec-potenciales-reduccion"><strong>potencial estándar de reducción, E°</strong></span> <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Mediciones de esta clase dan E°(Zn²⁺/Zn) = −0.76 V y E°(Cu²⁺/Cu) = +0.34 V, y la diferencia entre ambos, 1.10 V, reproduce el voltaje medido en la celda <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. El potencial estándar de una celda también se calcula, según Brown, restando el potencial del ánodo al del cátodo:</p>
<p><span id="eq-e0-celda"><span class="math display">\[E^\circ_{\text{celda}} = E^\circ_{\text{red}}(\text{cátodo}) - E^\circ_{\text{red}}(\text{ánodo}) \tag{20.3}\]</span></span></p>
<p>En la ecuación (<a href="#eq-e0-celda" class="quarto-xref">Ecuación&nbsp;<span>20.3</span></a>), E°celda es el potencial estándar de la celda completa y E°red los potenciales estándar de reducción de cátodo y ánodo, ambos medidos frente al EEH <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Para la celda de zinc y cobre, la resta da +0.34 − (−0.76) = +1.10 V, y el signo positivo anuncia una reacción espontánea <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Cuanto mayor sea E°celda, mayor será la fuerza impulsora de la reacción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Conviene anticipar una discrepancia de notación entre las fuentes: Pauling define el potencial de la celda como la resta del potencial del electrodo escrito a la izquierda menos el de la derecha, con semirreacciones tabuladas para producir un solo electrón, mientras Oriakhi suma el potencial de oxidación al de reducción, siendo el primero el negativo del segundo <span class="citation" data-cites="pauling1988 oriakhi2021">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15-5-15-6</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.2</a>)</span>. Las tres formulaciones son equivalentes, y su diferencia es solo de convención de signos, una fuente clásica de errores que conviene reconocer <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. El resultado físico, el voltaje medido, no depende de la notación elegida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>La tabla 20.1 de Brown, de la que se reproducen valores representativos, ordena las semirreacciones de reducción por su E° <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. La lectura se hace de arriba hacia abajo: las especies de las filas superiores se reducen con facilidad, mientras las inferiores tienden a oxidarse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<div class="table-responsive">
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Semirreacción de reducción</th>
<th style="text-align: center;">E° (V)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">F₂ + 2e⁻ → 2F⁻</td>
<td style="text-align: center;">+2.87</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cl₂ + 2e⁻ → 2Cl⁻</td>
<td style="text-align: center;">+1.36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O</td>
<td style="text-align: center;">+1.33</td>
</tr>
<tr class="even">
<td style="text-align: left;">O₂ + 4H⁺ + 4e⁻ → 2H₂O</td>
<td style="text-align: center;">+1.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ag⁺ + e⁻ → Ag</td>
<td style="text-align: center;">+0.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">I₂ + 2e⁻ → 2I⁻</td>
<td style="text-align: center;">+0.54</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cu²⁺ + 2e⁻ → Cu</td>
<td style="text-align: center;">+0.34</td>
</tr>
<tr class="even">
<td style="text-align: left;">2H⁺ + 2e⁻ → H₂</td>
<td style="text-align: center;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Pb²⁺ + 2e⁻ → Pb</td>
<td style="text-align: center;">−0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ni²⁺ + 2e⁻ → Ni</td>
<td style="text-align: center;">−0.28</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zn²⁺ + 2e⁻ → Zn</td>
<td style="text-align: center;">−0.76</td>
</tr>
<tr class="even">
<td style="text-align: left;">Al³⁺ + 3e⁻ → Al</td>
<td style="text-align: center;">−1.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mg²⁺ + 2e⁻ → Mg</td>
<td style="text-align: center;">−2.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">Li⁺ + e⁻ → Li</td>
<td style="text-align: center;">−3.05</td>
</tr>
</tbody>
</table>
</div>
<p>La tabla coloca arriba a los mejores agentes oxidantes, como el flúor y el cloro, y abajo a los mejores reductores, como el litio y el magnesio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Una semirreacción con E° grande y positivo procede como reducción y obliga a la otra, situada más abajo, a invertirse y oxidarse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Así, el dicromato (E° = +1.33 V) oxida al yoduro (E° = +0.54 V) con un potencial de celda de 0.79 V, mientras el fluoruro, que exige +2.87 V, no puede ser oxidado por el cloro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. La escala de potenciales generaliza, con números, la serie de actividad cualitativa del capítulo 5 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
</section>
<section id="energía-libre-trabajo-eléctrico-y-constante-de-equilibrio" class="level2">
<h2 class="anchored" data-anchor-id="energía-libre-trabajo-eléctrico-y-constante-de-equilibrio">Energía libre, trabajo eléctrico y constante de equilibrio</h2>
<p>Un voltaje positivo significa que la reacción de celda es espontánea, y su magnitud mide la fuerza impulsora termodinámica <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. La conexión cuantitativa con el capítulo 18 es directa, pues la energía libre de Gibbs y el potencial de celda se relacionan mediante la carga total transferida <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. La <strong>constante de Faraday, F</strong>, definida como la carga de un mol de electrones, vale 96 485 C/mol y convierte los moles de electrones n en culombios <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p><span id="eq-dg-e"><span class="math display">\[\Delta G^\circ = -n F E^\circ \tag{20.4}\]</span></span></p>
<p>En la ecuación (<a href="#eq-dg-e" class="quarto-xref">Ecuación&nbsp;<span>20.4</span></a>), n es el número de moles de electrones transferidos según la reacción como está escrita, F la constante de Faraday y E° el potencial estándar de la celda <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. El signo negativo hace que un voltaje positivo produzca una energía libre negativa, la condición de espontaneidad del capítulo 18 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Como E° es una propiedad intensiva, multiplicar la ecuación por un factor no altera el potencial, aunque sí cambian n, ΔG° y la constante de equilibrio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Y como ΔG° = −RT ln K, la ecuación (<a href="#eq-dg-e" class="quarto-xref">Ecuación&nbsp;<span>20.4</span></a>) se transforma también en el puente electroquímico hacia las constantes del capítulo 15, que a 25 °C toma la forma <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>:</p>
<p><span id="eq-logk"><span class="math display">\[\log K = \frac{nE^\circ}{0.0592} \tag{20.5}\]</span></span></p>
<p>La ecuación (<a href="#eq-logk" class="quarto-xref">Ecuación&nbsp;<span>20.5</span></a>) permite obtener constantes de equilibrio extremas sin medir concentraciones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Para la oxidación de la plata por el oxígeno en medio ácido, 4Ag + O₂ + 4H⁺ → 4Ag⁺ + 2H₂O, con E° = 1.23 − 0.80 = +0.43 V y n = 4, la constante resulta del orden de 10²⁹ y la energía libre, −170 kJ por mol de reacción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. El mismo cálculo, invertido, predice la constante de equilibrio de cualquier reacción redox a partir de los datos de tabla <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>La máxima cantidad de trabajo útil que la celda puede entregar vale w_max = −nFE, y su potencia se obtiene multiplicando el voltaje por la corriente en amperios <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Un vatio es un julio por segundo, y el kilovatio-hora de las facturas eléctricas equivale a 3.6 × 10⁶ J <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Para forzar la reacción inversa en una electrólisis, el voltaje aplicado debe superar el de la celda: si la celda se descarga con un potencial interno de 0.90 V en contra, se requiere un voltaje externo mayor que +0.90 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
</section>
<section id="la-ecuación-de-nernst-y-las-celdas-de-concentración" class="level2">
<h2 class="anchored" data-anchor-id="la-ecuación-de-nernst-y-las-celdas-de-concentración">La ecuación de Nernst y las celdas de concentración</h2>
<p>Fuera del estado estándar, el potencial depende de las concentraciones según la <span id="sec-ecuacion-nernst"><strong>ecuación de Nernst</strong></span> <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. Esta relación, que deriva del cociente de reacción Q del capítulo 15, corrige E° con el logaritmo de Q <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. A medida que la celda se descarga, Q se acerca a la constante K y el potencial tiende a cero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p><span id="eq-nernst"><span class="math display">\[E = E^\circ - \frac{RT}{nF} \ln Q \tag{20.6}\]</span></span></p>
<p>En la ecuación de Nernst (<a href="#eq-nernst" class="quarto-xref">Ecuación&nbsp;<span>20.6</span></a>), E es el potencial bajo las condiciones dadas, R la constante de los gases, T la temperatura absoluta, F la constante de Faraday y Q el cociente de reacción, evaluado con las concentraciones reales y sin incluir sólidos puros <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. A 25 °C, sustituyendo las constantes y expresando el logaritmo en base diez, la relación se simplifica:</p>
<p><span id="eq-nernst-298"><span class="math display">\[E = E^\circ - \frac{0.0592}{n} \log Q \tag{20.7}\]</span></span></p>
<p>Con la forma simplificada (<a href="#eq-nernst-298" class="quarto-xref">Ecuación&nbsp;<span>20.7</span></a>), la celda de zinc y cobre con [Cu²⁺] = 5.0 M y [Zn²⁺] = 0.050 M eleva su potencial de 1.10 V a 1.16 V, pues el exceso de ion cúprico desplaza la reacción hacia los productos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El cociente vale Q = 0.010 y el término 0.0296 log Q aporta +0.06 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. La misma ecuación predice qué ocurre al descargar la celda: las concentraciones se igualan y el voltaje decae <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>La célula nerviosa y el músculo cardíaco funcionan como <span id="sec-celdas-concentracion"><strong>celdas de concentración</strong></span> de iones potasio: el interior celular contiene unos 135 mM de K⁺ y el exterior unos 4 mM <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. La ecuación de Nernst aplicada a esta diferencia predice un potencial de reposo cercano a −90 mV <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El electrocardiograma registra precisamente estas fluctuaciones de potencial durante el latido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>Cuando ambas semiceldas usan el mismo par redox en concentraciones distintas, E° se cancela y el potencial proviene solo de la diferencia de concentración <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. La <strong>celda de concentración</strong> de níquel con 1.00 × 10⁻³ M frente a 1.00 M genera unos 0.09 V, y la de zinc con 3.75 × 10⁻⁴ M frente a 1.35 M, unos 0.105 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. En el electrodo sumergido en la disolución diluida, el metal se disuelve buscando igualar concentraciones, y ese electrodo diluido actúa como ánodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>El caso más útil de celda de concentración es el del hidrógeno, porque su potencial depende del pH <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–7</a>)</span>. Una celda con dos electrodos de hidrógeno, uno en disolución de pH conocido y otro en la muestra, produce 0.0592 V por unidad de pH, fundamento del medidor de pH o potenciómetro <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–7</a>)</span>. Brown resuelve el caso inverso: si el voltaje mide 0.211 V frente al electrodo estándar de hidrógeno, la disolución desconocida posee [H⁺] = 2.7 × 10⁻⁴ M, es decir, pH 3.56 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
</section>
<section id="baterías-y-celdas-de-combustible" class="level2">
<h2 class="anchored" data-anchor-id="baterías-y-celdas-de-combustible">Baterías y celdas de combustible</h2>
<p>Una <strong>batería</strong> es una fuente portátil y autónoma de energía formada por una o varias celdas voltaicas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>. Las pilas domésticas de 1.5 V son una sola celda, mientras la batería de 12 V del automóvil conecta en serie seis celdas de 2 V <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–8</a>)</span>. En una conexión en serie los voltajes se suman, y el electrodo positivo de cada celda es su cátodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>.</p>
<p>La batería de plomo-ácido descarga el plomo esponjoso del ánodo y el PbO₂ del cátodo, ambos sumergidos en ácido sulfúrico al 38% en masa, con densidad 1.290 g/cm³ cuando está cargada <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–8</a>)</span>. Las semirreacciones forman sulfato de plomo adherido a las placas, y la reacción global:</p>
<p><span id="eq-plomo-acido"><span class="math display">\[\mathrm{Pb}(s) + \mathrm{PbO}_2(s) + 2\mathrm{H}_2\mathrm{SO}_4(aq) \rightarrow 2\mathrm{PbSO}_4(s) + 2\mathrm{H}_2\mathrm{O}(l) \tag{20.8}\]</span></span></p>
<p>En la ecuación (<a href="#eq-plomo-acido" class="quarto-xref">Ecuación&nbsp;<span>20.8</span></a>) el mismo elemento cambia de estado de oxidación en ambas direcciones: el plomo metálico pasa de 0 a +2 oxidándose, y el del PbO₂ pasa de +4 a +2 reduciéndose <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–8</a>)</span>. Al descargarse, el ácido se consume y la densidad del electrolito cae, lo que permite medir la carga restante con un hidrómetro <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–8</a>)</span>. La recarga con el alternador invierte ambas semirreacciones y repone el ácido sulfúrico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>.</p>
<p>Las baterías recargables modernas varían los materiales: la de níquel-cadmio entrega 1.30 V por celda con ánodo de cadmio, pero el cadmio es tóxico y denso, y se producen anualmente unos 1 500 millones de estas baterías <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>. La de níquel-hidruro metálico (NiMH) conserva el cátodo y cambia el ánodo por una aleación como ZrNi₂ capaz de absorber hidrógeno atómico, que se oxida al descargarse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>. La de ion-litio alcanza unos 3.7 V con la inserción reversible de Li⁺ entre capas de óxido de cobalto y grafito, ofreciendo la mayor densidad de energía <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>.</p>
<p>Una <strong>celda de combustible</strong> recibe continuamente el combustible y el oxidante desde el exterior, en lugar de almacenarlos dentro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>. La celda de hidrógeno y oxígeno con membrana de intercambio protónico opera a unos 80 °C con platino como catalizador y produce cerca de un voltio por celda, de modo que varias apiladas alcanzan potencias útiles <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>.</p>
<p>La eficiencia máxima de convertir calor en electricidad ronda el 40%, y las celdas de combustible generan electricidad aproximadamente al doble de eficiencia que los mejores motores de combustión <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>. Una celda de metanol directo, cuyos productos son CO₂ y agua, promete transportar energía con menor huella de carbono <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7</a>)</span>.</p>
</section>
<section id="corrosión-la-descarga-espontánea-de-los-metales" class="level2">
<h2 class="anchored" data-anchor-id="corrosión-la-descarga-espontánea-de-los-metales">Corrosión: la descarga espontánea de los metales</h2>
<p>La <span id="sec-corrosion"><strong>corrosión</strong></span> es la oxidación espontánea de un metal en su entorno, y la herrumbre del hierro es su manifestación más costosa <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>. El hierro metálico, con E°(Fe²⁺/Fe) = −0.440 V, se oxida mientras el oxígeno se reduce, porque el potencial del par O₂/H₂O es más positivo que el del hierro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>. La formación de herrumbre exige simultáneamente oxígeno y agua, y el Fe²⁺ inicial se oxida después a Fe³⁺, que precipita como óxido hidratado <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>.</p>
<p>La velocidad de corrosión depende del entorno: la aceleran las sales, cuyos iones cierran el circuito eléctrico como un puente salino, y el contacto con metales más difíciles de oxidar que el hierro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>. La reducción del oxígeno requiere H⁺, de modo que un pH superior a 9 la bloquea y el hierro no se corroe <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>.</p>
<p>Las regiones deformadas o abolladas actúan como ánodos locales donde el metal se disuelve, mientras la herrumbre se deposita en el cátodo, la zona con mayor suministro de oxígeno <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>. Se estima que hasta el 20% de la producción anual de hierro en Estados Unidos reemplaza objetos descartados por daño de la herrumbre <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>.</p>
<p>El zinc protege al hierro mejor que una pintura porque se corroe en su lugar: al ser E°(Zn²⁺/Zn) = −0.763 V más negativo que el −0.440 V del hierro, el zinc se oxida preferentemente y actúa como <strong>ánodo de sacrificio</strong>, mientras el hierro queda como cátodo donde el oxígeno se reduce <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>.</p>
<p>Esta <strong>protección catódica</strong> se extiende a tuberías y tanques subterráneos, a los que se conecta un bloque de magnesio, con E° = −2.37 V, enterrado rodeado de yeso, sulfato de sodio y arcilla <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>. El aluminio, por su parte, se protege solo con una capa impermeable de Al₂O₃, y el acero inoxidable resiste gracias a sus elementos de aleación <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.8</a>)</span>.</p>
</section>
<section id="electrólisis-y-electrometalurgia" class="level2">
<h2 class="anchored" data-anchor-id="electrólisis-y-electrometalurgia">Electrólisis y electrometalurgia</h2>
<p>La <span id="sec-electrolisis"><strong>electrólisis</strong></span> invierte el proceso de la celda voltaica: aplicando un voltaje externo mayor que el de la celda en sentido contrario, se fuerza una reacción redox no espontánea <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. El dispositivo, llamado <strong>celda electrolítica</strong>, conecta el electrodo positivo de la fuente al ánodo y el negativo al cátodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. La electrólisis del cloruro de sodio fundido, que se funde a 801 °C, produce sodio metálico en el cátodo y cloro gaseoso en el ánodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>:</p>
<p><span id="eq-nacl"><span class="math display">\[2\mathrm{NaCl}(l) \rightarrow 2\mathrm{Na}(l) + \mathrm{Cl}_2(g) \tag{20.9}\]</span></span></p>
<p>En la ecuación (<a href="#eq-nacl" class="quarto-xref">Ecuación&nbsp;<span>20.9</span></a>), cada ion sodio gana un electrón en el cátodo y cada ion cloruro pierde uno en el ánodo, y la corriente sostiene el balance de cargas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. La industria abarata el proceso añadiendo carbonato de sodio para bajar el punto de fusión, y separa los productos con una pantalla de hierro que deja flotar el sodio líquido, más ligero que la sal fundida <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>. Solo una pequeña fracción del cloro estadounidense proviene de esta vía fundida, pues la mayor parte se obtiene de la salmuera <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>.</p>
<p>La razón para fundir la sal es la competencia del agua: en disolución acuosa, el agua admite reducción con potenciales de 0.00 V en medio ácido y −0.83 V en medio básico, mucho menos negativos que el −2.71 V del sodio, de modo que el agua se reduciría primero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
<p>Por eso los metales activos como sodio, magnesio y aluminio se obtienen por <strong>electrometalurgia</strong>, la producción de metales por electrólisis, desde sales fundidas <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. En la electrólisis de disoluciones solo se reducen u oxidan las especies más favorables, y la elección de electrodos inertes o activos decide el curso de la reacción <span class="citation" data-cites="brown2012 oriakhi2021">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.10</a>)</span>.</p>
<p>El cromado y el niquelado explotan un electrodo activo: en una disolución de NiSO₄, el cátodo de acero reduce el Ni²⁺, cuyo potencial estándar −0.28 V es menos negativo que el −0.83 V del agua, y el ánodo de níquel metálico se disuelve oxidándose <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Como ánodo y cátodo usan el mismo par, el potencial estándar de la celda es cero y basta un voltaje pequeño para depositar níquel <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. La masa depositada se controla con la carga: un coulomb equivale a un amperio por segundo, y la contabilidad de electrones cierra la ecuación:</p>
<p><span id="eq-faraday"><span class="math display">\[\text{mol } e^- = \frac{I\,t}{F} \tag{20.10}\]</span></span></p>
<p>En la ecuación (<a href="#eq-faraday" class="quarto-xref">Ecuación&nbsp;<span>20.10</span></a>), I es la corriente en amperios, t el tiempo en segundos y F la constante de Faraday, de modo que el producto It entrega directamente los moles de electrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Conviene advertir una discrepancia numérica entre las fuentes sobre F: Brown emplea 96 485 C/mol, Pauling 96 490 C y Oriakhi redondea a 96 500 C/mol <span class="citation" data-cites="brown2012 pauling1988 oriakhi2021">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>; <a href="../references.html#ref-oriakhi2021" role="doc-biblioref">Oriakhi 2021, sec. 23.10</a>)</span>. La diferencia refleja la precisión de las mediciones de cada época, y para los cálculos del capítulo se toma la cifra de Brown <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Faraday condensó sus observaciones en dos leyes que gobiernan toda electrólisis: la masa de sustancia transformada es proporcional a la carga circulante y, para una carga dada, proporcional al peso equivalente <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>. La ley resume el contenido de la ecuación (<a href="#eq-faraday" class="quarto-xref">Ecuación&nbsp;<span>20.10</span></a>) y de la estequiometría de cada semirreacción, como en el depósito de un mol de aluminio por cada tres moles de electrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Las dos tradiciones, la del peso equivalente de Pauling y la de los moles de electrones de Brown, describen el mismo hecho con unidades distintas <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
<p>El aluminio resume la economía de la electrometalurgia: su óxido funde por encima de 2000 °C, pero disuelto en criolita, Na₃AlF₆, funde a unos 1012 °C, temperatura accesible en celdas de unos 5 V <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>. Los ánodos de grafito se consumen en la reacción global del proceso Hall-Héroult:</p>
<p><span id="eq-hall"><span class="math display">\[2\mathrm{Al}_2\mathrm{O}_3 + 3\mathrm{C} \rightarrow 4\mathrm{Al} + 3\mathrm{CO}_2 \tag{20.11}\]</span></span></p>
<p>La ecuación (<a href="#eq-hall" class="quarto-xref">Ecuación&nbsp;<span>20.11</span></a>) muestra el doble papel del carbono, conductor eléctrico y reactivo que se oxida a dióxido <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Charles Hall en Estados Unidos y Paul Héroult en Francia descubrieron el proceso independientemente, con solo veintidós años, hacia 1886 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Hasta entonces el aluminio se obtenía reduciendo sus sales con sodio o potasio, y en 1852 costaba 545 dólares por libra, más que el oro <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Hoy la industria del aluminio consume alrededor del 2% de la electricidad de Estados Unidos, y reciclar aluminio exige solo el 5% de la energía de producirlo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
<p>La refinación electrolítica purifica el cobre de sus minerales: ánodos gruesos de cobre bruto se disuelven y el metal puro se deposita sobre cátodos delgados en un baño de sulfato de cobre <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>. Las impurezas nobles, oro, plata y platino, caen al fondo como lodo anódico, mientras las activas como el hierro permanecen en disolución <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>. La electrólisis de la salmuera produce además el cloro y la sosa cáustica de la industria química, con un cátodo de mercurio que forma una amalgama de sodio <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–9</a>)</span>.</p>
</section>
<section id="ejemplo-resuelto-la-celda-de-zinc-y-cobre-bajo-condiciones-reales" class="level2">
<h2 class="anchored" data-anchor-id="ejemplo-resuelto-la-celda-de-zinc-y-cobre-bajo-condiciones-reales">Ejemplo resuelto: la celda de zinc y cobre bajo condiciones reales</h2>
<p>El ejemplo integra la escala de potenciales, la energía libre y la ecuación de Nernst para responder qué ocurre cuando la celda clásica opera fuera del estado estándar <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5–20.6</a>)</span>. Con E°(Zn²⁺/Zn) = −0.76 V y E°(Cu²⁺/Cu) = +0.34 V, se pide calcular el potencial estándar de la celda, la energía libre estándar, la constante de equilibrio y el potencial cuando [Cu²⁺] = 2.5 M y [Zn²⁺] = 0.040 M <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4–20.6</a>)</span>.</p>
<p>El potencial estándar se obtiene de la ecuación (<a href="#eq-e0-celda" class="quarto-xref">Ecuación&nbsp;<span>20.3</span></a>): E° = +0.34 − (−0.76) = +1.10 V, y la energía libre, con la ecuación (<a href="#eq-dg-e" class="quarto-xref">Ecuación&nbsp;<span>20.4</span></a>) y n = 2, vale ΔG° = −2 × 96 485 × 1.10 = −212 kJ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. El signo negativo confirma la espontaneidad en condiciones estándar, y su magnitud, unos 212 kJ por mol de reacción, es la máxima cantidad de trabajo eléctrico recuperable si la celda operara reversiblemente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>La constante de equilibrio sale de la ecuación (<a href="#eq-logk" class="quarto-xref">Ecuación&nbsp;<span>20.5</span></a>): log K = 2 × 1.10/0.0592 = 37.2, de modo que K ≈ 1.4 × 10³⁷, un valor que desplaza la reacción abrumadoramente hacia el cobre metálico <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. En el equilibrio, el ion cúprico queda prácticamente agotado y la disolución contiene casi solo Zn²⁺ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Una constante tan extrema se obtiene sin esfuerzo por electroquímica, mientras medirla por análisis químico sería inviable <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Fuera del estado estándar, el cociente vale Q = [Zn²⁺]/[Cu²⁺] = 0.040/2.5 = 0.016, y la ecuación de Nernst (<a href="#eq-nernst-298" class="quarto-xref">Ecuación&nbsp;<span>20.7</span></a>) da E = 1.10 − 0.0296 × log(0.016) = 1.10 + 0.053 = 1.15 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El potencial supera al estándar porque el exceso de Cu²⁺ y la escasez de Zn²⁺ empujan la reacción hacia los productos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. Al descargarse la celda, la diferencia de concentraciones se erosiona, Q crece hasta K y el voltaje cae hacia cero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>El mismo formalismo explica las celdas de concentración: si ambas semiceldas fueran de cobre con [Cu²⁺] = 2.5 M y 0.040 M, el potencial sería E = 0.0296 log(2.5/0.040) = 0.053 V, con el electrodo diluido como ánodo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El resultado generaliza la lección del capítulo 18: la dirección del cambio depende de las condiciones, y la termodinámica cuantifica exactamente cuánta energía se libera o se exige <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
</section>
<section id="preguntas-y-ejercicios" class="level2">
<h2 class="anchored" data-anchor-id="preguntas-y-ejercicios">Preguntas y ejercicios</h2>
<p>Los ejercicios de este capítulo, inspirados en <span class="citation" data-cites="brown2012">Brown et&nbsp;al. (<a href="../references.html#ref-brown2012" role="doc-biblioref">2012</a>)</span> (2012), cap. 20; <span class="citation" data-cites="pauling1988">Pauling (<a href="../references.html#ref-pauling1988" role="doc-biblioref">1988</a>)</span> (1988), cap. 15; <span class="citation" data-cites="atkins2015">Atkins (<a href="../references.html#ref-atkins2015" role="doc-biblioref">2015</a>)</span> (2015), cap. 4; <span class="citation" data-cites="oriakhi2021">Oriakhi (<a href="../references.html#ref-oriakhi2021" role="doc-biblioref">2021</a>)</span> (2021), caps. 22-23, combinan la asignación de números de oxidación, el balanceo por semirreacciones, la predicción de espontaneidad, el cálculo de potenciales, energías libres y constantes, y la cuantificación de la electrólisis.</p>
<p>Primer ejercicio: determina el número de oxidación del cloro en el KClO₃, del nitrógeno en el ion amonio y del manganeso en el ion permanganato, aplicando las reglas del capítulo 5 y haciendo explícitas las cargas hipotéticas de cada átomo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>. Señala además cuál de las tres especies es el oxidante más fuerte <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Segundo ejercicio: balancea por el método de las semirreacciones la oxidación del ion bromuro por el dicromato en medio ácido, Br⁻ + Cr₂O₇²⁻ → BrO₃⁻ + Cr³⁺, indicando cuántos electrones se transfieren, qué especie se oxida y cuál actúa como agente oxidante <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>Tercer ejercicio: el yodo molecular se desproporciona en medio básico dando yoduro y yodato, I₂ + OH⁻ → I⁻ + IO₃⁻, en una reacción donde la misma sustancia se oxida y se reduce a la vez <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 20</a>, ej. 20.97)</span>. Balancea la ecuación ajustando el medio con agua e iones hidróxido y comprueba que la suma de cargas se conserva <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>Cuarto ejercicio: con zinc y níquel se construye una celda voltaica cuyas semiceldas son Zn²⁺/Zn y Ni²⁺/Ni <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Identifica ánodo y cátodo, el signo de cada electrodo, la dirección del flujo de electrones y de los iones del puente salino, y calcula el potencial estándar con la ecuación (<a href="#eq-e0-celda" class="quarto-xref">Ecuación&nbsp;<span>20.3</span></a>) <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Quinto ejercicio: decide si el ion Fe³⁺ oxida al cadmio metálico, sabiendo que el par Fe³⁺/Fe²⁺ tiene potencial estándar +0.771 V y que E°(Cd²⁺/Cd) = −0.403 V <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–6</a>)</span>. Escribe la reacción global, calcula su potencial estándar y predice si avanza hacia los productos <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Sexto ejercicio: para la celda de zinc y níquel del cuarto ejercicio, calcula la energía libre estándar, la constante de equilibrio y el trabajo eléctrico máximo que entrega al consumirse un mol de zinc, usando las ecuaciones (<a href="#eq-dg-e" class="quarto-xref">Ecuación&nbsp;<span>20.4</span></a>) y (<a href="#eq-logk" class="quarto-xref">Ecuación&nbsp;<span>20.5</span></a>) y expresando los resultados en kilojulios por mol de reacción <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Séptimo ejercicio: la misma celda de zinc y níquel opera con [Ni²⁺] = 0.10 M y [Zn²⁺] = 2.0 M <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. Calcula el cociente de reacción y el potencial con la ecuación de Nernst (<a href="#eq-nernst-298" class="quarto-xref">Ecuación&nbsp;<span>20.7</span></a>), y decide si el voltaje supera o queda por debajo del estándar <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>Octavo ejercicio: dos semiceldas de zinc, una con [Zn²⁺] = 2.5 M y otra con 5.0 × 10⁻³ M, forman una celda de concentración <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. Indica qué semicelda actúa como ánodo, calcula el potencial con la ecuación (<a href="#eq-nernst-298" class="quarto-xref">Ecuación&nbsp;<span>20.7</span></a>) y explica qué ocurre con las concentraciones al descargarse <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>Noveno ejercicio: una corriente de 10.0 A circula durante 2.00 h por una celda electrolítica con iones Cr³⁺ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Calcula con la ecuación (<a href="#eq-faraday" class="quarto-xref">Ecuación&nbsp;<span>20.10</span></a>) la masa de cromo depositada en el cátodo, tomando la masa molar del cromo como 52.0 g/mol <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
<p>Décimo ejercicio: dos celdas electrolíticas conectadas en serie depositan, la primera, plata desde Ag⁺ y la segunda, cobre desde Cu²⁺ <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>. Si se depositan 2.16 g de plata, calcula la masa de cobre depositada y el tiempo necesario con una corriente de 1.00 A <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>.</p>
</section>
<section id="solucionario" class="level2">
<h2 class="anchored" data-anchor-id="solucionario">Solucionario</h2>
<p>Primer ejercicio: el potasio aporta +1 y cada oxígeno −2, de modo que el cloro del KClO₃ debe ser +5 para que la suma de números de oxidación dé cero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>. En el ion amonio cada hidrógeno vale +1 y, con carga total +1, el nitrógeno resulta −3 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>. El permanganato, con cuatro oxígenos a −2 y carga −1, exige manganeso +7, el estado de oxidación máximo del elemento <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1</a>)</span>.</p>
<p>Segundo ejercicio: el bromuro se oxida a bromato cediendo seis electrones, Br⁻ + 3H₂O → BrO₃⁻ + 6H⁺ + 6e⁻, y el dicromato se reduce ganándolos, Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. Sumando y cancelando el agua y los protones comunes queda Cr₂O₇²⁻ + Br⁻ + 8H⁺ → 2Cr³⁺ + BrO₃⁻ + 4H₂O, con seis electrones transferidos: el bromo pasa de −1 a +5 y el cromo de +6 a +3 <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>Tercer ejercicio: la oxidación I₂ + 12OH⁻ → 2IO₃⁻ + 6H₂O + 10e⁻ y la reducción I₂ + 2e⁻ → 2I⁻ se combinan multiplicando la segunda por cinco: 6I₂ + 12OH⁻ → 10I⁻ + 2IO₃⁻ + 6H₂O, que simplificada da 3I₂ + 6OH⁻ → 5I⁻ + IO₃⁻ + 3H₂O <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>. La suma de cargas se conserva: −6 a la izquierda y −5 − 1 = −6 a la derecha <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.2</a>)</span>.</p>
<p>Cuarto ejercicio: el zinc, con E° = −0.76 V frente a −0.28 V del níquel, se oxida y es el ánodo negativo, mientras el níquel se reduce en el cátodo positivo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. Los electrones fluyen por el circuito externo del zinc al níquel, los cationes migran hacia el cátodo y los aniones hacia el ánodo, y el potencial estándar vale E° = −0.28 − (−0.76) = +0.48 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Quinto ejercicio: el cadmio se oxida cediendo dos electrones y el Fe³⁺ se reduce a Fe²⁺, de modo que la reacción global es 2Fe³⁺ + Cd → 2Fe²⁺ + Cd²⁺ con potencial E° = +0.771 − (−0.403) = +1.174 V <span class="citation" data-cites="pauling1988 brown2012">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–6</a>; <a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>. El voltaje positivo revela que el hierro(III) oxida al cadmio espontáneamente <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4</a>)</span>.</p>
<p>Sexto ejercicio: con n = 2 y E° = +0.48 V, la energía libre vale ΔG° = −2 × 96 485 × 0.48 = −92.6 kJ, y la constante, con log K = 2 × 0.48/0.0592 = 16.2, resulta K ≈ 1.7 × 10¹⁶ <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. El trabajo eléctrico máximo coincide con ΔG° en valor absoluto, 92.6 kJ por mol de zinc, porque la celda descargada reversiblemente convierte toda la energía libre en trabajo <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>.</p>
<p>Séptimo ejercicio: el cociente vale Q = 2.0/0.10 = 20, y el potencial, E = 0.48 − 0.0296 × log 20 = 0.48 − 0.0385 = 0.44 V <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El voltaje cae por debajo del estándar porque el producto Zn²⁺ abunda y el reactivo Ni²⁺ escasea, empujando la reacción hacia la izquierda <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>Octavo ejercicio: el electrodo sumergido en la disolución diluida es el ánodo, pues el zinc metálico se disuelve buscando igualar concentraciones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>. El potencial vale E = 0.0296 × log(2.5/0.005) = 0.0296 × 2.699 = 0.080 V, y al descargarse las dos concentraciones convergen mientras el voltaje cae a cero <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.6</a>)</span>.</p>
<p>Noveno ejercicio: la carga total vale Q = It = 10.0 × 7200 = 7.20 × 10⁴ C, que con la ecuación (<a href="#eq-faraday" class="quarto-xref">Ecuación&nbsp;<span>20.10</span></a>) corresponde a 0.746 mol de electrones <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. Cada ion Cr³⁺ exige tres electrones, de modo que se depositan 0.2487 mol de cromo, equivalentes a 0.2487 × 52.0 = 12.9 g <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>.</p>
<p>Décimo ejercicio: la plata monovalente consume un electrón por átomo, de modo que 0.0200 mol de plata equivalen a 0.0200 mol de electrones <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>. El cobre divalente deposita un átomo por cada dos electrones, 0.0100 mol, es decir 0.635 g, y el tiempo resulta t = 0.0200 × 96 485/1.00 = 1930 s, unos 32 minutos <span class="citation" data-cites="pauling1988">(<a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>.</p>
</section>
<section id="resumen" class="level2">
<h2 class="anchored" data-anchor-id="resumen">Resumen</h2>
<p>La electroquímica convierte la energía de las reacciones redox en trabajo eléctrico, midiendo en voltios la fuerza impulsora que antes se expresaba como energía libre de Gibbs <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, cap. 20</a>)</span>. La oxidación, generalizada como pérdida de electrones, se balancea por semirreacciones que luego se combinan en la ecuación global <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.1–20.2</a>)</span>. En la celda voltaica, la oxidación ocurre en el ánodo y la reducción en el cátodo, conectados por un puente salino <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.3</a>)</span>.</p>
<p>La escala de potenciales estándar nace del electrodo de hidrógeno y ordena oxidantes y reductores, mientras la ecuación de Nernst extiende las predicciones a cualquier concentración <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.4–20.6</a>)</span>. La energía libre, la constante de equilibrio y el trabajo máximo se entrelazan con el potencial mediante la constante de Faraday <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.5</a>)</span>. Baterías y celdas de combustible explotan estos principios, y la corrosión muestra su coste cuando el metal se disuelve sin permiso <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.7–20.8</a>)</span>.</p>
<p>La electrólisis invierte el flujo con un voltaje externo, obteniendo metales activos desde fundentes y refinando los pasivos, y las leyes de Faraday cuantifican la masa transformada <span class="citation" data-cites="brown2012 pauling1988">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>; <a href="../references.html#ref-pauling1988" role="doc-biblioref">Pauling 1988, sec. 15–4</a>)</span>. El aluminio de Hall-Héroult y el cobre refinado ilustran la escala industrial del principio <span class="citation" data-cites="brown2012">(<a href="../references.html#ref-brown2012" role="doc-biblioref">Brown et&nbsp;al. 2012, sec. 20.9</a>)</span>. En suma, un solo marco, el de la transferencia de electrones, gobierna desde la batería del automóvil hasta la fotosíntesis <span class="citation" data-cites="atkins2015">(<a href="../references.html#ref-atkins2015" role="doc-biblioref">Atkins 2015, cap. 4</a>)</span>.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-atkins2015" class="csl-entry" role="listitem">
Atkins, Peter. 2015. <em>Chemistry: A Very Short Introduction</em>. 1st ed. Oxford University Press. <a href="https://doi.org/10.1093/actrade/9780199683970.001.0001">https://doi.org/10.1093/actrade/9780199683970.001.0001</a>.
</div>
<div id="ref-brown2012" class="csl-entry" role="listitem">
Brown, Theodore L., H. Eugene LeMay, Bruce E. Bursten, Catherine J. Murphy, y Patrick M. Woodward. 2012. <em>Chemistry: The Central Science</em>. 12th ed. Pearson Prentice Hall.
</div>
<div id="ref-chang2022" class="csl-entry" role="listitem">
Chang, Raymond, y Jason Overby. 2022. <em>Chemistry</em>. 14th (ISE). McGraw-Hill Education.
</div>
<div id="ref-oriakhi2021" class="csl-entry" role="listitem">
Oriakhi, Christopher O. 2021. <em>Chemistry in Quantitative Language: Fundamentals of General Chemistry Calculations</em>. 2nd ed. Oxford University Press.
</div>
<div id="ref-pauling1988" class="csl-entry" role="listitem">
Pauling, Linus. 1988. <em>General Chemistry</em>. 3rd (reprinted). Dover Publications.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiado");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiado");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../02_quimica/18-termodinamica-quimica.html" class="pagination-link" aria-label="Termodinámica química">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Termodinámica química</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../02_quimica/20-quimica-nuclear.html" class="pagination-link" aria-label="Química nuclear">
        <span class="nav-page-text"><span class="chapter-title">Química nuclear</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>