# La base física de la herencia

## La herencia y los genes

La herencia es un proceso donde unos rasgos se transmiten a la descendencia de un organismo. Para que ocurra la herencia necesitamos genes. Los genes codifican información necesaria para producir diferentes estructuras celulares [@audesirk2013].

## Los genes y su ubicación en el cromosoma

Los genes se encuentran en los cromosomas, que son estructuras de ADN empaquetadas por unas proteínas llamadas histonas. En esta cadena larga hay segmentos específicos de ADN con longitudes variables que se identifican como los genes [@audesirk2013].

Al evaluar la posición de un solo gen en la cadena larga de ADN empaquetada conocida como cromosoma, esa posición ya identificada se conoce como locus. Ahora bien, si me refiero a varias posiciones de varios genes en el cromosoma se dice loci [@audesirk2013].

## Cromosomas homólogos y alelos

Los cromosomas están en pares y se llaman cromosomas homólogos. Un par homólogo tiene los mismos genes en los mismos loci. Pero hay ocasiones en que en un homólogo su gen en determinado locus sea diferente al del otro cromosoma homólogo [@audesirk2013]. Es decir, el gen del cromosoma homólogo 1 es diferente al gen del cromosoma homólogo 2. A este gen que en determinado locus es diferente entre los cromosomas homólogos se le conoce como alelo [@audesirk2013].

## Las mutaciones como fuente de alelos

¿Por qué un gen en determinado locus es un alelo? Esto ocurre por la mutación de ese gen. La mutación ocurre en el óvulo o espermatozoide de nuestros antecesores y esto pudo ocurrir hace cientos de años. Sin embargo, puede ocurrir en nuestros progenitores, pero esto es muy raro [@audesirk2013].

## Homocigotos y heterocigotos

Cuando tenemos un gen o genes en el mismo locus o loci y son idénticos, indicamos que este gen es homocigoto, pero para los genes en un locus que son diferentes (es decir, cuando los alelos son diferentes) se conoce como heterocigoto [@audesirk2013]. Donde homocigoto desde el griego se indica como mismo par y heterocigoto del griego es diferente par [@audesirk2013].

## Descubrimiento de los principios de la herencia

Uno de los primeros en estudiar la herencia fue Mendel. Para cualquier experimento exitoso en biología hay tres pasos clave: elegir un sistema adecuado, diseñar y realizar el experimento de manera correcta, y analizar los datos en forma adecuada. Mendel fue el primer genetista en completar los tres pasos. Mendel eligió el guisante comestible para sus experimentos. Las estructuras reproductivas masculinas de una flor se llaman estambres y producen polen, cada grano de polen contiene espermatozoides. La estructura reproductiva femenina se llama carpelo, que tiene un ovario donde se ubican los óvulos. Los guisantes se autofecundan porque los pétalos encierran todas las estructuras reproductivas. Cuando el espermatozoide de un organismo fecunda sus propios óvulos, el proceso se llama autofecundación. Mendel hizo dos técnicas: la primera era aprovechar la autofecundación, y la segunda era quitarle a una flor sus estambres para que no se autofecundara, luego usar el polen de otra flor para fecundar la flor que se le quitó sus estambres. Cuando el espermatozoide de un organismo fecunda los óvulos de un organismo diferente, el proceso se llama fecundación cruzada. El diseño de Mendel era simple, pero brillante. Estudió rasgos con formas inequívocamente diferentes, como flores blancas frente a moradas. También comenzó por estudiar sólo un rasgo a la vez, a diferencia de los primeros investigadores que intentaban estudiar todas las características de organismos completos simultáneamente. Mendel hizo varias generaciones para ver qué sucedía y contó el número de descendientes con cada tipo de rasgo, usando análisis numérico e interpretación estadística, algo innovador en su época [@audesirk2013].
